package com.ymatou.payment.infrastructure.db.model;

import java.math.BigDecimal;
import java.util.Date;

public class AccountingLogPo {
    /**
     * BIGINT(19) 必填<br>
     * 
     */
    private Long id;

    /**
     * TIMESTAMP(23,3) 默认值[(getdate())] 必填<br>
     * 
     */
    private Date createdTime;

    /**
     * DECIMAL(18,2) 必填<br>
     * 
     */
    private BigDecimal accoutingAmt;

    /**
     * VARCHAR(32) 必填<br>
     * 
     */
    private String accountingType;

    /**
     * INTEGER(10) 必填<br>
     * 
     */
    private Integer status;

    /**
     * BIGINT(19) 必填<br>
     * 
     */
    private Long userId;

    /**
     * VARCHAR(32) 必填<br>
     * 
     */
    private String bizNo;

    /**
     * VARCHAR(16) 必填<br>
     * 
     */
    private String respCode;

    /**
     * VARCHAR(255)<br>
     * 
     */
    private String respMsg;

    /**
     * VARCHAR(32)<br>
     * 
     */
    private String memo;

    /**
     * BIGINT(19) 必填<br>
     */
    public Long getId() {
        return id;
    }

    /**
     * BIGINT(19) 必填<br>
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * TIMESTAMP(23,3) 默认值[(getdate())] 必填<br>
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * TIMESTAMP(23,3) 默认值[(getdate())] 必填<br>
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * DECIMAL(18,2) 必填<br>
     */
    public BigDecimal getAccoutingAmt() {
        return accoutingAmt;
    }

    /**
     * DECIMAL(18,2) 必填<br>
     */
    public void setAccoutingAmt(BigDecimal accoutingAmt) {
        this.accoutingAmt = accoutingAmt;
    }

    /**
     * VARCHAR(32) 必填<br>
     */
    public String getAccountingType() {
        return accountingType;
    }

    /**
     * VARCHAR(32) 必填<br>
     */
    public void setAccountingType(String accountingType) {
        this.accountingType = accountingType == null ? null : accountingType.trim();
    }

    /**
     * INTEGER(10) 必填<br>
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * INTEGER(10) 必填<br>
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * BIGINT(19) 必填<br>
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * BIGINT(19) 必填<br>
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * VARCHAR(32) 必填<br>
     */
    public String getBizNo() {
        return bizNo;
    }

    /**
     * VARCHAR(32) 必填<br>
     */
    public void setBizNo(String bizNo) {
        this.bizNo = bizNo == null ? null : bizNo.trim();
    }

    /**
     * VARCHAR(16) 必填<br>
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * VARCHAR(16) 必填<br>
     */
    public void setRespCode(String respCode) {
        this.respCode = respCode == null ? null : respCode.trim();
    }

    /**
     * VARCHAR(255)<br>
     */
    public String getRespMsg() {
        return respMsg;
    }

    /**
     * VARCHAR(255)<br>
     */
    public void setRespMsg(String respMsg) {
        this.respMsg = respMsg == null ? null : respMsg.trim();
    }

    /**
     * VARCHAR(32)<br>
     */
    public String getMemo() {
        return memo;
    }

    /**
     * VARCHAR(32)<br>
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_AccoutingLog
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", accoutingAmt=").append(accoutingAmt);
        sb.append(", accountingType=").append(accountingType);
        sb.append(", status=").append(status);
        sb.append(", userId=").append(userId);
        sb.append(", bizNo=").append(bizNo);
        sb.append(", respCode=").append(respCode);
        sb.append(", respMsg=").append(respMsg);
        sb.append(", memo=").append(memo);
        sb.append("]");
        return sb.toString();
    }
}