package com.ymatou.payment.infrastructure.db.model;

import java.math.BigDecimal;
import java.util.Date;

public class AccountingLogPo {
    /**
     * BIGINT(19) 必填<br>
     * 
     */
    private Long ID;

    /**
     * TIMESTAMP(23,3)<br>
     * 
     */
    private Date createdTime;

    /**
     * DECIMAL(18,2)<br>
     * 
     */
    private BigDecimal accoutingAmt;

    /**
     * VARCHAR(32)<br>
     * 
     */
    private String accountingType;

    /**
     * INTEGER(10)<br>
     * 
     */
    private Integer status;

    /**
     * VARCHAR(16)<br>
     * 
     */
    private String accountId;

    /**
     * VARCHAR(32)<br>
     * 
     */
    private String bizNo;

    /**
     * VARCHAR(16)<br>
     * 
     */
    private String respCode;

    /**
     * VARCHAR(255)<br>
     * 
     */
    private String respMsg;

    /**
     * VARCHAR(32)<br>
     * 
     */
    private String MEMO;

    /**
     * BIGINT(19) 必填<br>
     */
    public Long getID() {
        return ID;
    }

    /**
     * BIGINT(19) 必填<br>
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * TIMESTAMP(23,3)<br>
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * TIMESTAMP(23,3)<br>
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * DECIMAL(18,2)<br>
     */
    public BigDecimal getAccoutingAmt() {
        return accoutingAmt;
    }

    /**
     * DECIMAL(18,2)<br>
     */
    public void setAccoutingAmt(BigDecimal accoutingAmt) {
        this.accoutingAmt = accoutingAmt;
    }

    /**
     * VARCHAR(32)<br>
     */
    public String getAccountingType() {
        return accountingType;
    }

    /**
     * VARCHAR(32)<br>
     */
    public void setAccountingType(String accountingType) {
        this.accountingType = accountingType == null ? null : accountingType.trim();
    }

    /**
     * INTEGER(10)<br>
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * INTEGER(10)<br>
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * VARCHAR(16)<br>
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * VARCHAR(16)<br>
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * VARCHAR(32)<br>
     */
    public String getBizNo() {
        return bizNo;
    }

    /**
     * VARCHAR(32)<br>
     */
    public void setBizNo(String bizNo) {
        this.bizNo = bizNo == null ? null : bizNo.trim();
    }

    /**
     * VARCHAR(16)<br>
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * VARCHAR(16)<br>
     */
    public void setRespCode(String respCode) {
        this.respCode = respCode == null ? null : respCode.trim();
    }

    /**
     * VARCHAR(255)<br>
     */
    public String getRespMsg() {
        return respMsg;
    }

    /**
     * VARCHAR(255)<br>
     */
    public void setRespMsg(String respMsg) {
        this.respMsg = respMsg == null ? null : respMsg.trim();
    }

    /**
     * VARCHAR(32)<br>
     */
    public String getMEMO() {
        return MEMO;
    }

    /**
     * VARCHAR(32)<br>
     */
    public void setMEMO(String MEMO) {
        this.MEMO = MEMO == null ? null : MEMO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_AccoutingLog
     *
     * @mbggenerated Tue Jun 07 15:47:31 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ID=").append(ID);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", accoutingAmt=").append(accoutingAmt);
        sb.append(", accountingType=").append(accountingType);
        sb.append(", status=").append(status);
        sb.append(", accountId=").append(accountId);
        sb.append(", bizNo=").append(bizNo);
        sb.append(", respCode=").append(respCode);
        sb.append(", respMsg=").append(respMsg);
        sb.append(", MEMO=").append(MEMO);
        sb.append("]");
        return sb.toString();
    }
}