package com.ymatou.payment.infrastructure.db.model;

import java.util.Date;

public class AlipayNotifyLogPo {
    /**
     * INTEGER(10) 必填<br>
     * 
     */
    private Integer iId;

    /**
     * TIMESTAMP(23,3) 默认值[(getdate())] 必填<br>
     * 
     */
    private Date dAddTime;

    /**
     * VARCHAR(50) 默认值[('##')]<br>
     * 
     */
    private String bizNo;

    /**
     * CLOB(2147483647)<br>
     * 
     */
    private String sParameters;

    /**
     * INTEGER(10) 必填<br>
     */
    public Integer getiId() {
        return iId;
    }

    /**
     * INTEGER(10) 必填<br>
     */
    public void setiId(Integer iId) {
        this.iId = iId;
    }

    /**
     * TIMESTAMP(23,3) 默认值[(getdate())] 必填<br>
     */
    public Date getdAddTime() {
        return dAddTime;
    }

    /**
     * TIMESTAMP(23,3) 默认值[(getdate())] 必填<br>
     */
    public void setdAddTime(Date dAddTime) {
        this.dAddTime = dAddTime;
    }

    /**
     * VARCHAR(50) 默认值[('##')]<br>
     */
    public String getBizNo() {
        return bizNo;
    }

    /**
     * VARCHAR(50) 默认值[('##')]<br>
     */
    public void setBizNo(String bizNo) {
        this.bizNo = bizNo == null ? null : bizNo.trim();
    }

    /**
     * CLOB(2147483647)<br>
     */
    public String getsParameters() {
        return sParameters;
    }

    /**
     * CLOB(2147483647)<br>
     */
    public void setsParameters(String sParameters) {
        this.sParameters = sParameters == null ? null : sParameters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", iId=").append(iId);
        sb.append(", dAddTime=").append(dAddTime);
        sb.append(", bizNo=").append(bizNo);
        sb.append(", sParameters=").append(sParameters);
        sb.append("]");
        return sb.toString();
    }
}