package com.ymatou.payment.infrastructure.db.model;

import java.util.Date;

public class AlipaynotifylogPo {
    /**
     * INTEGER(10) 必填<br>
     * 
     */
    private Integer iid;

    /**
     * TIMESTAMP(23,3) 默认值[(getdate())] 必填<br>
     * 
     */
    private Date daddtime;

    /**
     * VARCHAR(50) 默认值[('##')]<br>
     * 
     */
    private String bizno;

    /**
     * CLOB(2147483647)<br>
     * 
     */
    private String sparameters;

    /**
     * INTEGER(10) 必填<br>
     */
    public Integer getIid() {
        return iid;
    }

    /**
     * INTEGER(10) 必填<br>
     */
    public void setIid(Integer iid) {
        this.iid = iid;
    }

    /**
     * TIMESTAMP(23,3) 默认值[(getdate())] 必填<br>
     */
    public Date getDaddtime() {
        return daddtime;
    }

    /**
     * TIMESTAMP(23,3) 默认值[(getdate())] 必填<br>
     */
    public void setDaddtime(Date daddtime) {
        this.daddtime = daddtime;
    }

    /**
     * VARCHAR(50) 默认值[('##')]<br>
     */
    public String getBizno() {
        return bizno;
    }

    /**
     * VARCHAR(50) 默认值[('##')]<br>
     */
    public void setBizno(String bizno) {
        this.bizno = bizno == null ? null : bizno.trim();
    }

    /**
     * CLOB(2147483647)<br>
     */
    public String getSparameters() {
        return sparameters;
    }

    /**
     * CLOB(2147483647)<br>
     */
    public void setSparameters(String sparameters) {
        this.sparameters = sparameters == null ? null : sparameters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Fri May 20 14:09:31 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", iid=").append(iid);
        sb.append(", daddtime=").append(daddtime);
        sb.append(", bizno=").append(bizno);
        sb.append(", sparameters=").append(sparameters);
        sb.append("]");
        return sb.toString();
    }
}