package com.ymatou.payment.infrastructure.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CmbAggrementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    public CmbAggrementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAggIdIsNull() {
            addCriterion("AggId is null");
            return (Criteria) this;
        }

        public Criteria andAggIdIsNotNull() {
            addCriterion("AggId is not null");
            return (Criteria) this;
        }

        public Criteria andAggIdEqualTo(Long value) {
            addCriterion("AggId =", value, "aggId");
            return (Criteria) this;
        }

        public Criteria andAggIdNotEqualTo(Long value) {
            addCriterion("AggId <>", value, "aggId");
            return (Criteria) this;
        }

        public Criteria andAggIdGreaterThan(Long value) {
            addCriterion("AggId >", value, "aggId");
            return (Criteria) this;
        }

        public Criteria andAggIdGreaterThanOrEqualTo(Long value) {
            addCriterion("AggId >=", value, "aggId");
            return (Criteria) this;
        }

        public Criteria andAggIdLessThan(Long value) {
            addCriterion("AggId <", value, "aggId");
            return (Criteria) this;
        }

        public Criteria andAggIdLessThanOrEqualTo(Long value) {
            addCriterion("AggId <=", value, "aggId");
            return (Criteria) this;
        }

        public Criteria andAggIdIn(List<Long> values) {
            addCriterion("AggId in", values, "aggId");
            return (Criteria) this;
        }

        public Criteria andAggIdNotIn(List<Long> values) {
            addCriterion("AggId not in", values, "aggId");
            return (Criteria) this;
        }

        public Criteria andAggIdBetween(Long value1, Long value2) {
            addCriterion("AggId between", value1, value2, "aggId");
            return (Criteria) this;
        }

        public Criteria andAggIdNotBetween(Long value1, Long value2) {
            addCriterion("AggId not between", value1, value2, "aggId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("UserId is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("UserId is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("UserId =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("UserId <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("UserId >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("UserId >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("UserId <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("UserId <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("UserId in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("UserId not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("UserId between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("UserId not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAggStatusIsNull() {
            addCriterion("AggStatus is null");
            return (Criteria) this;
        }

        public Criteria andAggStatusIsNotNull() {
            addCriterion("AggStatus is not null");
            return (Criteria) this;
        }

        public Criteria andAggStatusEqualTo(Integer value) {
            addCriterion("AggStatus =", value, "aggStatus");
            return (Criteria) this;
        }

        public Criteria andAggStatusNotEqualTo(Integer value) {
            addCriterion("AggStatus <>", value, "aggStatus");
            return (Criteria) this;
        }

        public Criteria andAggStatusGreaterThan(Integer value) {
            addCriterion("AggStatus >", value, "aggStatus");
            return (Criteria) this;
        }

        public Criteria andAggStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("AggStatus >=", value, "aggStatus");
            return (Criteria) this;
        }

        public Criteria andAggStatusLessThan(Integer value) {
            addCriterion("AggStatus <", value, "aggStatus");
            return (Criteria) this;
        }

        public Criteria andAggStatusLessThanOrEqualTo(Integer value) {
            addCriterion("AggStatus <=", value, "aggStatus");
            return (Criteria) this;
        }

        public Criteria andAggStatusIn(List<Integer> values) {
            addCriterion("AggStatus in", values, "aggStatus");
            return (Criteria) this;
        }

        public Criteria andAggStatusNotIn(List<Integer> values) {
            addCriterion("AggStatus not in", values, "aggStatus");
            return (Criteria) this;
        }

        public Criteria andAggStatusBetween(Integer value1, Integer value2) {
            addCriterion("AggStatus between", value1, value2, "aggStatus");
            return (Criteria) this;
        }

        public Criteria andAggStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("AggStatus not between", value1, value2, "aggStatus");
            return (Criteria) this;
        }

        public Criteria andSignDateTimeIsNull() {
            addCriterion("SignDateTime is null");
            return (Criteria) this;
        }

        public Criteria andSignDateTimeIsNotNull() {
            addCriterion("SignDateTime is not null");
            return (Criteria) this;
        }

        public Criteria andSignDateTimeEqualTo(String value) {
            addCriterion("SignDateTime =", value, "signDateTime");
            return (Criteria) this;
        }

        public Criteria andSignDateTimeNotEqualTo(String value) {
            addCriterion("SignDateTime <>", value, "signDateTime");
            return (Criteria) this;
        }

        public Criteria andSignDateTimeGreaterThan(String value) {
            addCriterion("SignDateTime >", value, "signDateTime");
            return (Criteria) this;
        }

        public Criteria andSignDateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("SignDateTime >=", value, "signDateTime");
            return (Criteria) this;
        }

        public Criteria andSignDateTimeLessThan(String value) {
            addCriterion("SignDateTime <", value, "signDateTime");
            return (Criteria) this;
        }

        public Criteria andSignDateTimeLessThanOrEqualTo(String value) {
            addCriterion("SignDateTime <=", value, "signDateTime");
            return (Criteria) this;
        }

        public Criteria andSignDateTimeLike(String value) {
            addCriterion("SignDateTime like", value, "signDateTime");
            return (Criteria) this;
        }

        public Criteria andSignDateTimeNotLike(String value) {
            addCriterion("SignDateTime not like", value, "signDateTime");
            return (Criteria) this;
        }

        public Criteria andSignDateTimeIn(List<String> values) {
            addCriterion("SignDateTime in", values, "signDateTime");
            return (Criteria) this;
        }

        public Criteria andSignDateTimeNotIn(List<String> values) {
            addCriterion("SignDateTime not in", values, "signDateTime");
            return (Criteria) this;
        }

        public Criteria andSignDateTimeBetween(String value1, String value2) {
            addCriterion("SignDateTime between", value1, value2, "signDateTime");
            return (Criteria) this;
        }

        public Criteria andSignDateTimeNotBetween(String value1, String value2) {
            addCriterion("SignDateTime not between", value1, value2, "signDateTime");
            return (Criteria) this;
        }

        public Criteria andRespCodeIsNull() {
            addCriterion("RespCode is null");
            return (Criteria) this;
        }

        public Criteria andRespCodeIsNotNull() {
            addCriterion("RespCode is not null");
            return (Criteria) this;
        }

        public Criteria andRespCodeEqualTo(String value) {
            addCriterion("RespCode =", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeNotEqualTo(String value) {
            addCriterion("RespCode <>", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeGreaterThan(String value) {
            addCriterion("RespCode >", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeGreaterThanOrEqualTo(String value) {
            addCriterion("RespCode >=", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeLessThan(String value) {
            addCriterion("RespCode <", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeLessThanOrEqualTo(String value) {
            addCriterion("RespCode <=", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeLike(String value) {
            addCriterion("RespCode like", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeNotLike(String value) {
            addCriterion("RespCode not like", value, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeIn(List<String> values) {
            addCriterion("RespCode in", values, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeNotIn(List<String> values) {
            addCriterion("RespCode not in", values, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeBetween(String value1, String value2) {
            addCriterion("RespCode between", value1, value2, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespCodeNotBetween(String value1, String value2) {
            addCriterion("RespCode not between", value1, value2, "respCode");
            return (Criteria) this;
        }

        public Criteria andRespMessageIsNull() {
            addCriterion("RespMessage is null");
            return (Criteria) this;
        }

        public Criteria andRespMessageIsNotNull() {
            addCriterion("RespMessage is not null");
            return (Criteria) this;
        }

        public Criteria andRespMessageEqualTo(String value) {
            addCriterion("RespMessage =", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageNotEqualTo(String value) {
            addCriterion("RespMessage <>", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageGreaterThan(String value) {
            addCriterion("RespMessage >", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageGreaterThanOrEqualTo(String value) {
            addCriterion("RespMessage >=", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageLessThan(String value) {
            addCriterion("RespMessage <", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageLessThanOrEqualTo(String value) {
            addCriterion("RespMessage <=", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageLike(String value) {
            addCriterion("RespMessage like", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageNotLike(String value) {
            addCriterion("RespMessage not like", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageIn(List<String> values) {
            addCriterion("RespMessage in", values, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageNotIn(List<String> values) {
            addCriterion("RespMessage not in", values, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageBetween(String value1, String value2) {
            addCriterion("RespMessage between", value1, value2, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageNotBetween(String value1, String value2) {
            addCriterion("RespMessage not between", value1, value2, "respMessage");
            return (Criteria) this;
        }

        public Criteria andBankSerialNoIsNull() {
            addCriterion("BankSerialNo is null");
            return (Criteria) this;
        }

        public Criteria andBankSerialNoIsNotNull() {
            addCriterion("BankSerialNo is not null");
            return (Criteria) this;
        }

        public Criteria andBankSerialNoEqualTo(String value) {
            addCriterion("BankSerialNo =", value, "bankSerialNo");
            return (Criteria) this;
        }

        public Criteria andBankSerialNoNotEqualTo(String value) {
            addCriterion("BankSerialNo <>", value, "bankSerialNo");
            return (Criteria) this;
        }

        public Criteria andBankSerialNoGreaterThan(String value) {
            addCriterion("BankSerialNo >", value, "bankSerialNo");
            return (Criteria) this;
        }

        public Criteria andBankSerialNoGreaterThanOrEqualTo(String value) {
            addCriterion("BankSerialNo >=", value, "bankSerialNo");
            return (Criteria) this;
        }

        public Criteria andBankSerialNoLessThan(String value) {
            addCriterion("BankSerialNo <", value, "bankSerialNo");
            return (Criteria) this;
        }

        public Criteria andBankSerialNoLessThanOrEqualTo(String value) {
            addCriterion("BankSerialNo <=", value, "bankSerialNo");
            return (Criteria) this;
        }

        public Criteria andBankSerialNoLike(String value) {
            addCriterion("BankSerialNo like", value, "bankSerialNo");
            return (Criteria) this;
        }

        public Criteria andBankSerialNoNotLike(String value) {
            addCriterion("BankSerialNo not like", value, "bankSerialNo");
            return (Criteria) this;
        }

        public Criteria andBankSerialNoIn(List<String> values) {
            addCriterion("BankSerialNo in", values, "bankSerialNo");
            return (Criteria) this;
        }

        public Criteria andBankSerialNoNotIn(List<String> values) {
            addCriterion("BankSerialNo not in", values, "bankSerialNo");
            return (Criteria) this;
        }

        public Criteria andBankSerialNoBetween(String value1, String value2) {
            addCriterion("BankSerialNo between", value1, value2, "bankSerialNo");
            return (Criteria) this;
        }

        public Criteria andBankSerialNoNotBetween(String value1, String value2) {
            addCriterion("BankSerialNo not between", value1, value2, "bankSerialNo");
            return (Criteria) this;
        }

        public Criteria andUserPidTypeIsNull() {
            addCriterion("UserPidType is null");
            return (Criteria) this;
        }

        public Criteria andUserPidTypeIsNotNull() {
            addCriterion("UserPidType is not null");
            return (Criteria) this;
        }

        public Criteria andUserPidTypeEqualTo(String value) {
            addCriterion("UserPidType =", value, "userPidType");
            return (Criteria) this;
        }

        public Criteria andUserPidTypeNotEqualTo(String value) {
            addCriterion("UserPidType <>", value, "userPidType");
            return (Criteria) this;
        }

        public Criteria andUserPidTypeGreaterThan(String value) {
            addCriterion("UserPidType >", value, "userPidType");
            return (Criteria) this;
        }

        public Criteria andUserPidTypeGreaterThanOrEqualTo(String value) {
            addCriterion("UserPidType >=", value, "userPidType");
            return (Criteria) this;
        }

        public Criteria andUserPidTypeLessThan(String value) {
            addCriterion("UserPidType <", value, "userPidType");
            return (Criteria) this;
        }

        public Criteria andUserPidTypeLessThanOrEqualTo(String value) {
            addCriterion("UserPidType <=", value, "userPidType");
            return (Criteria) this;
        }

        public Criteria andUserPidTypeLike(String value) {
            addCriterion("UserPidType like", value, "userPidType");
            return (Criteria) this;
        }

        public Criteria andUserPidTypeNotLike(String value) {
            addCriterion("UserPidType not like", value, "userPidType");
            return (Criteria) this;
        }

        public Criteria andUserPidTypeIn(List<String> values) {
            addCriterion("UserPidType in", values, "userPidType");
            return (Criteria) this;
        }

        public Criteria andUserPidTypeNotIn(List<String> values) {
            addCriterion("UserPidType not in", values, "userPidType");
            return (Criteria) this;
        }

        public Criteria andUserPidTypeBetween(String value1, String value2) {
            addCriterion("UserPidType between", value1, value2, "userPidType");
            return (Criteria) this;
        }

        public Criteria andUserPidTypeNotBetween(String value1, String value2) {
            addCriterion("UserPidType not between", value1, value2, "userPidType");
            return (Criteria) this;
        }

        public Criteria andUserPidHashIsNull() {
            addCriterion("UserPidHash is null");
            return (Criteria) this;
        }

        public Criteria andUserPidHashIsNotNull() {
            addCriterion("UserPidHash is not null");
            return (Criteria) this;
        }

        public Criteria andUserPidHashEqualTo(String value) {
            addCriterion("UserPidHash =", value, "userPidHash");
            return (Criteria) this;
        }

        public Criteria andUserPidHashNotEqualTo(String value) {
            addCriterion("UserPidHash <>", value, "userPidHash");
            return (Criteria) this;
        }

        public Criteria andUserPidHashGreaterThan(String value) {
            addCriterion("UserPidHash >", value, "userPidHash");
            return (Criteria) this;
        }

        public Criteria andUserPidHashGreaterThanOrEqualTo(String value) {
            addCriterion("UserPidHash >=", value, "userPidHash");
            return (Criteria) this;
        }

        public Criteria andUserPidHashLessThan(String value) {
            addCriterion("UserPidHash <", value, "userPidHash");
            return (Criteria) this;
        }

        public Criteria andUserPidHashLessThanOrEqualTo(String value) {
            addCriterion("UserPidHash <=", value, "userPidHash");
            return (Criteria) this;
        }

        public Criteria andUserPidHashLike(String value) {
            addCriterion("UserPidHash like", value, "userPidHash");
            return (Criteria) this;
        }

        public Criteria andUserPidHashNotLike(String value) {
            addCriterion("UserPidHash not like", value, "userPidHash");
            return (Criteria) this;
        }

        public Criteria andUserPidHashIn(List<String> values) {
            addCriterion("UserPidHash in", values, "userPidHash");
            return (Criteria) this;
        }

        public Criteria andUserPidHashNotIn(List<String> values) {
            addCriterion("UserPidHash not in", values, "userPidHash");
            return (Criteria) this;
        }

        public Criteria andUserPidHashBetween(String value1, String value2) {
            addCriterion("UserPidHash between", value1, value2, "userPidHash");
            return (Criteria) this;
        }

        public Criteria andUserPidHashNotBetween(String value1, String value2) {
            addCriterion("UserPidHash not between", value1, value2, "userPidHash");
            return (Criteria) this;
        }

        public Criteria andNoPwdPayIsNull() {
            addCriterion("NoPwdPay is null");
            return (Criteria) this;
        }

        public Criteria andNoPwdPayIsNotNull() {
            addCriterion("NoPwdPay is not null");
            return (Criteria) this;
        }

        public Criteria andNoPwdPayEqualTo(String value) {
            addCriterion("NoPwdPay =", value, "noPwdPay");
            return (Criteria) this;
        }

        public Criteria andNoPwdPayNotEqualTo(String value) {
            addCriterion("NoPwdPay <>", value, "noPwdPay");
            return (Criteria) this;
        }

        public Criteria andNoPwdPayGreaterThan(String value) {
            addCriterion("NoPwdPay >", value, "noPwdPay");
            return (Criteria) this;
        }

        public Criteria andNoPwdPayGreaterThanOrEqualTo(String value) {
            addCriterion("NoPwdPay >=", value, "noPwdPay");
            return (Criteria) this;
        }

        public Criteria andNoPwdPayLessThan(String value) {
            addCriterion("NoPwdPay <", value, "noPwdPay");
            return (Criteria) this;
        }

        public Criteria andNoPwdPayLessThanOrEqualTo(String value) {
            addCriterion("NoPwdPay <=", value, "noPwdPay");
            return (Criteria) this;
        }

        public Criteria andNoPwdPayLike(String value) {
            addCriterion("NoPwdPay like", value, "noPwdPay");
            return (Criteria) this;
        }

        public Criteria andNoPwdPayNotLike(String value) {
            addCriterion("NoPwdPay not like", value, "noPwdPay");
            return (Criteria) this;
        }

        public Criteria andNoPwdPayIn(List<String> values) {
            addCriterion("NoPwdPay in", values, "noPwdPay");
            return (Criteria) this;
        }

        public Criteria andNoPwdPayNotIn(List<String> values) {
            addCriterion("NoPwdPay not in", values, "noPwdPay");
            return (Criteria) this;
        }

        public Criteria andNoPwdPayBetween(String value1, String value2) {
            addCriterion("NoPwdPay between", value1, value2, "noPwdPay");
            return (Criteria) this;
        }

        public Criteria andNoPwdPayNotBetween(String value1, String value2) {
            addCriterion("NoPwdPay not between", value1, value2, "noPwdPay");
            return (Criteria) this;
        }

        public Criteria andCancelTypeIsNull() {
            addCriterion("CancelType is null");
            return (Criteria) this;
        }

        public Criteria andCancelTypeIsNotNull() {
            addCriterion("CancelType is not null");
            return (Criteria) this;
        }

        public Criteria andCancelTypeEqualTo(Integer value) {
            addCriterion("CancelType =", value, "cancelType");
            return (Criteria) this;
        }

        public Criteria andCancelTypeNotEqualTo(Integer value) {
            addCriterion("CancelType <>", value, "cancelType");
            return (Criteria) this;
        }

        public Criteria andCancelTypeGreaterThan(Integer value) {
            addCriterion("CancelType >", value, "cancelType");
            return (Criteria) this;
        }

        public Criteria andCancelTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("CancelType >=", value, "cancelType");
            return (Criteria) this;
        }

        public Criteria andCancelTypeLessThan(Integer value) {
            addCriterion("CancelType <", value, "cancelType");
            return (Criteria) this;
        }

        public Criteria andCancelTypeLessThanOrEqualTo(Integer value) {
            addCriterion("CancelType <=", value, "cancelType");
            return (Criteria) this;
        }

        public Criteria andCancelTypeIn(List<Integer> values) {
            addCriterion("CancelType in", values, "cancelType");
            return (Criteria) this;
        }

        public Criteria andCancelTypeNotIn(List<Integer> values) {
            addCriterion("CancelType not in", values, "cancelType");
            return (Criteria) this;
        }

        public Criteria andCancelTypeBetween(Integer value1, Integer value2) {
            addCriterion("CancelType between", value1, value2, "cancelType");
            return (Criteria) this;
        }

        public Criteria andCancelTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("CancelType not between", value1, value2, "cancelType");
            return (Criteria) this;
        }

        public Criteria andCancelBankSerialNoIsNull() {
            addCriterion("CancelBankSerialNo is null");
            return (Criteria) this;
        }

        public Criteria andCancelBankSerialNoIsNotNull() {
            addCriterion("CancelBankSerialNo is not null");
            return (Criteria) this;
        }

        public Criteria andCancelBankSerialNoEqualTo(String value) {
            addCriterion("CancelBankSerialNo =", value, "cancelBankSerialNo");
            return (Criteria) this;
        }

        public Criteria andCancelBankSerialNoNotEqualTo(String value) {
            addCriterion("CancelBankSerialNo <>", value, "cancelBankSerialNo");
            return (Criteria) this;
        }

        public Criteria andCancelBankSerialNoGreaterThan(String value) {
            addCriterion("CancelBankSerialNo >", value, "cancelBankSerialNo");
            return (Criteria) this;
        }

        public Criteria andCancelBankSerialNoGreaterThanOrEqualTo(String value) {
            addCriterion("CancelBankSerialNo >=", value, "cancelBankSerialNo");
            return (Criteria) this;
        }

        public Criteria andCancelBankSerialNoLessThan(String value) {
            addCriterion("CancelBankSerialNo <", value, "cancelBankSerialNo");
            return (Criteria) this;
        }

        public Criteria andCancelBankSerialNoLessThanOrEqualTo(String value) {
            addCriterion("CancelBankSerialNo <=", value, "cancelBankSerialNo");
            return (Criteria) this;
        }

        public Criteria andCancelBankSerialNoLike(String value) {
            addCriterion("CancelBankSerialNo like", value, "cancelBankSerialNo");
            return (Criteria) this;
        }

        public Criteria andCancelBankSerialNoNotLike(String value) {
            addCriterion("CancelBankSerialNo not like", value, "cancelBankSerialNo");
            return (Criteria) this;
        }

        public Criteria andCancelBankSerialNoIn(List<String> values) {
            addCriterion("CancelBankSerialNo in", values, "cancelBankSerialNo");
            return (Criteria) this;
        }

        public Criteria andCancelBankSerialNoNotIn(List<String> values) {
            addCriterion("CancelBankSerialNo not in", values, "cancelBankSerialNo");
            return (Criteria) this;
        }

        public Criteria andCancelBankSerialNoBetween(String value1, String value2) {
            addCriterion("CancelBankSerialNo between", value1, value2, "cancelBankSerialNo");
            return (Criteria) this;
        }

        public Criteria andCancelBankSerialNoNotBetween(String value1, String value2) {
            addCriterion("CancelBankSerialNo not between", value1, value2, "cancelBankSerialNo");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("CreatedTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("CreatedTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("CreatedTime =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("CreatedTime <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("CreatedTime >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreatedTime >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("CreatedTime <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("CreatedTime <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("CreatedTime in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("CreatedTime not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("CreatedTime between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("CreatedTime not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeIsNull() {
            addCriterion("LastUpdatedTime is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeIsNotNull() {
            addCriterion("LastUpdatedTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeEqualTo(Date value) {
            addCriterion("LastUpdatedTime =", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeNotEqualTo(Date value) {
            addCriterion("LastUpdatedTime <>", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeGreaterThan(Date value) {
            addCriterion("LastUpdatedTime >", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LastUpdatedTime >=", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeLessThan(Date value) {
            addCriterion("LastUpdatedTime <", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("LastUpdatedTime <=", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeIn(List<Date> values) {
            addCriterion("LastUpdatedTime in", values, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeNotIn(List<Date> values) {
            addCriterion("LastUpdatedTime not in", values, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeBetween(Date value1, Date value2) {
            addCriterion("LastUpdatedTime between", value1, value2, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("LastUpdatedTime not between", value1, value2, "lastUpdatedTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 18 17:11:29 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Fri Nov 18 17:11:29 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}