package com.ymatou.payment.infrastructure.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CompensateprocessinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    public CompensateprocessinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCompensateidIsNull() {
            addCriterion("CompensateId is null");
            return (Criteria) this;
        }

        public Criteria andCompensateidIsNotNull() {
            addCriterion("CompensateId is not null");
            return (Criteria) this;
        }

        public Criteria andCompensateidEqualTo(Long value) {
            addCriterion("CompensateId =", value, "compensateid");
            return (Criteria) this;
        }

        public Criteria andCompensateidNotEqualTo(Long value) {
            addCriterion("CompensateId <>", value, "compensateid");
            return (Criteria) this;
        }

        public Criteria andCompensateidGreaterThan(Long value) {
            addCriterion("CompensateId >", value, "compensateid");
            return (Criteria) this;
        }

        public Criteria andCompensateidGreaterThanOrEqualTo(Long value) {
            addCriterion("CompensateId >=", value, "compensateid");
            return (Criteria) this;
        }

        public Criteria andCompensateidLessThan(Long value) {
            addCriterion("CompensateId <", value, "compensateid");
            return (Criteria) this;
        }

        public Criteria andCompensateidLessThanOrEqualTo(Long value) {
            addCriterion("CompensateId <=", value, "compensateid");
            return (Criteria) this;
        }

        public Criteria andCompensateidIn(List<Long> values) {
            addCriterion("CompensateId in", values, "compensateid");
            return (Criteria) this;
        }

        public Criteria andCompensateidNotIn(List<Long> values) {
            addCriterion("CompensateId not in", values, "compensateid");
            return (Criteria) this;
        }

        public Criteria andCompensateidBetween(Long value1, Long value2) {
            addCriterion("CompensateId between", value1, value2, "compensateid");
            return (Criteria) this;
        }

        public Criteria andCompensateidNotBetween(Long value1, Long value2) {
            addCriterion("CompensateId not between", value1, value2, "compensateid");
            return (Criteria) this;
        }

        public Criteria andCorrelateidIsNull() {
            addCriterion("CorrelateId is null");
            return (Criteria) this;
        }

        public Criteria andCorrelateidIsNotNull() {
            addCriterion("CorrelateId is not null");
            return (Criteria) this;
        }

        public Criteria andCorrelateidEqualTo(String value) {
            addCriterion("CorrelateId =", value, "correlateid");
            return (Criteria) this;
        }

        public Criteria andCorrelateidNotEqualTo(String value) {
            addCriterion("CorrelateId <>", value, "correlateid");
            return (Criteria) this;
        }

        public Criteria andCorrelateidGreaterThan(String value) {
            addCriterion("CorrelateId >", value, "correlateid");
            return (Criteria) this;
        }

        public Criteria andCorrelateidGreaterThanOrEqualTo(String value) {
            addCriterion("CorrelateId >=", value, "correlateid");
            return (Criteria) this;
        }

        public Criteria andCorrelateidLessThan(String value) {
            addCriterion("CorrelateId <", value, "correlateid");
            return (Criteria) this;
        }

        public Criteria andCorrelateidLessThanOrEqualTo(String value) {
            addCriterion("CorrelateId <=", value, "correlateid");
            return (Criteria) this;
        }

        public Criteria andCorrelateidLike(String value) {
            addCriterion("CorrelateId like", value, "correlateid");
            return (Criteria) this;
        }

        public Criteria andCorrelateidNotLike(String value) {
            addCriterion("CorrelateId not like", value, "correlateid");
            return (Criteria) this;
        }

        public Criteria andCorrelateidIn(List<String> values) {
            addCriterion("CorrelateId in", values, "correlateid");
            return (Criteria) this;
        }

        public Criteria andCorrelateidNotIn(List<String> values) {
            addCriterion("CorrelateId not in", values, "correlateid");
            return (Criteria) this;
        }

        public Criteria andCorrelateidBetween(String value1, String value2) {
            addCriterion("CorrelateId between", value1, value2, "correlateid");
            return (Criteria) this;
        }

        public Criteria andCorrelateidNotBetween(String value1, String value2) {
            addCriterion("CorrelateId not between", value1, value2, "correlateid");
            return (Criteria) this;
        }

        public Criteria andAppidIsNull() {
            addCriterion("AppId is null");
            return (Criteria) this;
        }

        public Criteria andAppidIsNotNull() {
            addCriterion("AppId is not null");
            return (Criteria) this;
        }

        public Criteria andAppidEqualTo(String value) {
            addCriterion("AppId =", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotEqualTo(String value) {
            addCriterion("AppId <>", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThan(String value) {
            addCriterion("AppId >", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThanOrEqualTo(String value) {
            addCriterion("AppId >=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThan(String value) {
            addCriterion("AppId <", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThanOrEqualTo(String value) {
            addCriterion("AppId <=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLike(String value) {
            addCriterion("AppId like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotLike(String value) {
            addCriterion("AppId not like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidIn(List<String> values) {
            addCriterion("AppId in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotIn(List<String> values) {
            addCriterion("AppId not in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidBetween(String value1, String value2) {
            addCriterion("AppId between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotBetween(String value1, String value2) {
            addCriterion("AppId not between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNull() {
            addCriterion("PayType is null");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNotNull() {
            addCriterion("PayType is not null");
            return (Criteria) this;
        }

        public Criteria andPaytypeEqualTo(String value) {
            addCriterion("PayType =", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotEqualTo(String value) {
            addCriterion("PayType <>", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThan(String value) {
            addCriterion("PayType >", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThanOrEqualTo(String value) {
            addCriterion("PayType >=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThan(String value) {
            addCriterion("PayType <", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThanOrEqualTo(String value) {
            addCriterion("PayType <=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLike(String value) {
            addCriterion("PayType like", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotLike(String value) {
            addCriterion("PayType not like", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeIn(List<String> values) {
            addCriterion("PayType in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotIn(List<String> values) {
            addCriterion("PayType not in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeBetween(String value1, String value2) {
            addCriterion("PayType between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotBetween(String value1, String value2) {
            addCriterion("PayType not between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andMethodnameIsNull() {
            addCriterion("MethodName is null");
            return (Criteria) this;
        }

        public Criteria andMethodnameIsNotNull() {
            addCriterion("MethodName is not null");
            return (Criteria) this;
        }

        public Criteria andMethodnameEqualTo(String value) {
            addCriterion("MethodName =", value, "methodname");
            return (Criteria) this;
        }

        public Criteria andMethodnameNotEqualTo(String value) {
            addCriterion("MethodName <>", value, "methodname");
            return (Criteria) this;
        }

        public Criteria andMethodnameGreaterThan(String value) {
            addCriterion("MethodName >", value, "methodname");
            return (Criteria) this;
        }

        public Criteria andMethodnameGreaterThanOrEqualTo(String value) {
            addCriterion("MethodName >=", value, "methodname");
            return (Criteria) this;
        }

        public Criteria andMethodnameLessThan(String value) {
            addCriterion("MethodName <", value, "methodname");
            return (Criteria) this;
        }

        public Criteria andMethodnameLessThanOrEqualTo(String value) {
            addCriterion("MethodName <=", value, "methodname");
            return (Criteria) this;
        }

        public Criteria andMethodnameLike(String value) {
            addCriterion("MethodName like", value, "methodname");
            return (Criteria) this;
        }

        public Criteria andMethodnameNotLike(String value) {
            addCriterion("MethodName not like", value, "methodname");
            return (Criteria) this;
        }

        public Criteria andMethodnameIn(List<String> values) {
            addCriterion("MethodName in", values, "methodname");
            return (Criteria) this;
        }

        public Criteria andMethodnameNotIn(List<String> values) {
            addCriterion("MethodName not in", values, "methodname");
            return (Criteria) this;
        }

        public Criteria andMethodnameBetween(String value1, String value2) {
            addCriterion("MethodName between", value1, value2, "methodname");
            return (Criteria) this;
        }

        public Criteria andMethodnameNotBetween(String value1, String value2) {
            addCriterion("MethodName not between", value1, value2, "methodname");
            return (Criteria) this;
        }

        public Criteria andRequesturlIsNull() {
            addCriterion("RequestUrl is null");
            return (Criteria) this;
        }

        public Criteria andRequesturlIsNotNull() {
            addCriterion("RequestUrl is not null");
            return (Criteria) this;
        }

        public Criteria andRequesturlEqualTo(String value) {
            addCriterion("RequestUrl =", value, "requesturl");
            return (Criteria) this;
        }

        public Criteria andRequesturlNotEqualTo(String value) {
            addCriterion("RequestUrl <>", value, "requesturl");
            return (Criteria) this;
        }

        public Criteria andRequesturlGreaterThan(String value) {
            addCriterion("RequestUrl >", value, "requesturl");
            return (Criteria) this;
        }

        public Criteria andRequesturlGreaterThanOrEqualTo(String value) {
            addCriterion("RequestUrl >=", value, "requesturl");
            return (Criteria) this;
        }

        public Criteria andRequesturlLessThan(String value) {
            addCriterion("RequestUrl <", value, "requesturl");
            return (Criteria) this;
        }

        public Criteria andRequesturlLessThanOrEqualTo(String value) {
            addCriterion("RequestUrl <=", value, "requesturl");
            return (Criteria) this;
        }

        public Criteria andRequesturlLike(String value) {
            addCriterion("RequestUrl like", value, "requesturl");
            return (Criteria) this;
        }

        public Criteria andRequesturlNotLike(String value) {
            addCriterion("RequestUrl not like", value, "requesturl");
            return (Criteria) this;
        }

        public Criteria andRequesturlIn(List<String> values) {
            addCriterion("RequestUrl in", values, "requesturl");
            return (Criteria) this;
        }

        public Criteria andRequesturlNotIn(List<String> values) {
            addCriterion("RequestUrl not in", values, "requesturl");
            return (Criteria) this;
        }

        public Criteria andRequesturlBetween(String value1, String value2) {
            addCriterion("RequestUrl between", value1, value2, "requesturl");
            return (Criteria) this;
        }

        public Criteria andRequesturlNotBetween(String value1, String value2) {
            addCriterion("RequestUrl not between", value1, value2, "requesturl");
            return (Criteria) this;
        }

        public Criteria andRetrycountIsNull() {
            addCriterion("RetryCount is null");
            return (Criteria) this;
        }

        public Criteria andRetrycountIsNotNull() {
            addCriterion("RetryCount is not null");
            return (Criteria) this;
        }

        public Criteria andRetrycountEqualTo(Integer value) {
            addCriterion("RetryCount =", value, "retrycount");
            return (Criteria) this;
        }

        public Criteria andRetrycountNotEqualTo(Integer value) {
            addCriterion("RetryCount <>", value, "retrycount");
            return (Criteria) this;
        }

        public Criteria andRetrycountGreaterThan(Integer value) {
            addCriterion("RetryCount >", value, "retrycount");
            return (Criteria) this;
        }

        public Criteria andRetrycountGreaterThanOrEqualTo(Integer value) {
            addCriterion("RetryCount >=", value, "retrycount");
            return (Criteria) this;
        }

        public Criteria andRetrycountLessThan(Integer value) {
            addCriterion("RetryCount <", value, "retrycount");
            return (Criteria) this;
        }

        public Criteria andRetrycountLessThanOrEqualTo(Integer value) {
            addCriterion("RetryCount <=", value, "retrycount");
            return (Criteria) this;
        }

        public Criteria andRetrycountIn(List<Integer> values) {
            addCriterion("RetryCount in", values, "retrycount");
            return (Criteria) this;
        }

        public Criteria andRetrycountNotIn(List<Integer> values) {
            addCriterion("RetryCount not in", values, "retrycount");
            return (Criteria) this;
        }

        public Criteria andRetrycountBetween(Integer value1, Integer value2) {
            addCriterion("RetryCount between", value1, value2, "retrycount");
            return (Criteria) this;
        }

        public Criteria andRetrycountNotBetween(Integer value1, Integer value2) {
            addCriterion("RetryCount not between", value1, value2, "retrycount");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeIsNull() {
            addCriterion("CreatedTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeIsNotNull() {
            addCriterion("CreatedTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeEqualTo(Date value) {
            addCriterion("CreatedTime =", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeNotEqualTo(Date value) {
            addCriterion("CreatedTime <>", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeGreaterThan(Date value) {
            addCriterion("CreatedTime >", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreatedTime >=", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeLessThan(Date value) {
            addCriterion("CreatedTime <", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeLessThanOrEqualTo(Date value) {
            addCriterion("CreatedTime <=", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeIn(List<Date> values) {
            addCriterion("CreatedTime in", values, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeNotIn(List<Date> values) {
            addCriterion("CreatedTime not in", values, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeBetween(Date value1, Date value2) {
            addCriterion("CreatedTime between", value1, value2, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeNotBetween(Date value1, Date value2) {
            addCriterion("CreatedTime not between", value1, value2, "createdtime");
            return (Criteria) this;
        }

        public Criteria andProcessmachinenameIsNull() {
            addCriterion("ProcessMachineName is null");
            return (Criteria) this;
        }

        public Criteria andProcessmachinenameIsNotNull() {
            addCriterion("ProcessMachineName is not null");
            return (Criteria) this;
        }

        public Criteria andProcessmachinenameEqualTo(String value) {
            addCriterion("ProcessMachineName =", value, "processmachinename");
            return (Criteria) this;
        }

        public Criteria andProcessmachinenameNotEqualTo(String value) {
            addCriterion("ProcessMachineName <>", value, "processmachinename");
            return (Criteria) this;
        }

        public Criteria andProcessmachinenameGreaterThan(String value) {
            addCriterion("ProcessMachineName >", value, "processmachinename");
            return (Criteria) this;
        }

        public Criteria andProcessmachinenameGreaterThanOrEqualTo(String value) {
            addCriterion("ProcessMachineName >=", value, "processmachinename");
            return (Criteria) this;
        }

        public Criteria andProcessmachinenameLessThan(String value) {
            addCriterion("ProcessMachineName <", value, "processmachinename");
            return (Criteria) this;
        }

        public Criteria andProcessmachinenameLessThanOrEqualTo(String value) {
            addCriterion("ProcessMachineName <=", value, "processmachinename");
            return (Criteria) this;
        }

        public Criteria andProcessmachinenameLike(String value) {
            addCriterion("ProcessMachineName like", value, "processmachinename");
            return (Criteria) this;
        }

        public Criteria andProcessmachinenameNotLike(String value) {
            addCriterion("ProcessMachineName not like", value, "processmachinename");
            return (Criteria) this;
        }

        public Criteria andProcessmachinenameIn(List<String> values) {
            addCriterion("ProcessMachineName in", values, "processmachinename");
            return (Criteria) this;
        }

        public Criteria andProcessmachinenameNotIn(List<String> values) {
            addCriterion("ProcessMachineName not in", values, "processmachinename");
            return (Criteria) this;
        }

        public Criteria andProcessmachinenameBetween(String value1, String value2) {
            addCriterion("ProcessMachineName between", value1, value2, "processmachinename");
            return (Criteria) this;
        }

        public Criteria andProcessmachinenameNotBetween(String value1, String value2) {
            addCriterion("ProcessMachineName not between", value1, value2, "processmachinename");
            return (Criteria) this;
        }

        public Criteria andLastprocessedtimeIsNull() {
            addCriterion("LastProcessedTime is null");
            return (Criteria) this;
        }

        public Criteria andLastprocessedtimeIsNotNull() {
            addCriterion("LastProcessedTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastprocessedtimeEqualTo(Date value) {
            addCriterion("LastProcessedTime =", value, "lastprocessedtime");
            return (Criteria) this;
        }

        public Criteria andLastprocessedtimeNotEqualTo(Date value) {
            addCriterion("LastProcessedTime <>", value, "lastprocessedtime");
            return (Criteria) this;
        }

        public Criteria andLastprocessedtimeGreaterThan(Date value) {
            addCriterion("LastProcessedTime >", value, "lastprocessedtime");
            return (Criteria) this;
        }

        public Criteria andLastprocessedtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LastProcessedTime >=", value, "lastprocessedtime");
            return (Criteria) this;
        }

        public Criteria andLastprocessedtimeLessThan(Date value) {
            addCriterion("LastProcessedTime <", value, "lastprocessedtime");
            return (Criteria) this;
        }

        public Criteria andLastprocessedtimeLessThanOrEqualTo(Date value) {
            addCriterion("LastProcessedTime <=", value, "lastprocessedtime");
            return (Criteria) this;
        }

        public Criteria andLastprocessedtimeIn(List<Date> values) {
            addCriterion("LastProcessedTime in", values, "lastprocessedtime");
            return (Criteria) this;
        }

        public Criteria andLastprocessedtimeNotIn(List<Date> values) {
            addCriterion("LastProcessedTime not in", values, "lastprocessedtime");
            return (Criteria) this;
        }

        public Criteria andLastprocessedtimeBetween(Date value1, Date value2) {
            addCriterion("LastProcessedTime between", value1, value2, "lastprocessedtime");
            return (Criteria) this;
        }

        public Criteria andLastprocessedtimeNotBetween(Date value1, Date value2) {
            addCriterion("LastProcessedTime not between", value1, value2, "lastprocessedtime");
            return (Criteria) this;
        }

        public Criteria andProcessstatusIsNull() {
            addCriterion("ProcessStatus is null");
            return (Criteria) this;
        }

        public Criteria andProcessstatusIsNotNull() {
            addCriterion("ProcessStatus is not null");
            return (Criteria) this;
        }

        public Criteria andProcessstatusEqualTo(Integer value) {
            addCriterion("ProcessStatus =", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusNotEqualTo(Integer value) {
            addCriterion("ProcessStatus <>", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusGreaterThan(Integer value) {
            addCriterion("ProcessStatus >", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("ProcessStatus >=", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusLessThan(Integer value) {
            addCriterion("ProcessStatus <", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusLessThanOrEqualTo(Integer value) {
            addCriterion("ProcessStatus <=", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusIn(List<Integer> values) {
            addCriterion("ProcessStatus in", values, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusNotIn(List<Integer> values) {
            addCriterion("ProcessStatus not in", values, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusBetween(Integer value1, Integer value2) {
            addCriterion("ProcessStatus between", value1, value2, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("ProcessStatus not between", value1, value2, "processstatus");
            return (Criteria) this;
        }

        public Criteria andCompensatetypeIsNull() {
            addCriterion("CompensateType is null");
            return (Criteria) this;
        }

        public Criteria andCompensatetypeIsNotNull() {
            addCriterion("CompensateType is not null");
            return (Criteria) this;
        }

        public Criteria andCompensatetypeEqualTo(Integer value) {
            addCriterion("CompensateType =", value, "compensatetype");
            return (Criteria) this;
        }

        public Criteria andCompensatetypeNotEqualTo(Integer value) {
            addCriterion("CompensateType <>", value, "compensatetype");
            return (Criteria) this;
        }

        public Criteria andCompensatetypeGreaterThan(Integer value) {
            addCriterion("CompensateType >", value, "compensatetype");
            return (Criteria) this;
        }

        public Criteria andCompensatetypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("CompensateType >=", value, "compensatetype");
            return (Criteria) this;
        }

        public Criteria andCompensatetypeLessThan(Integer value) {
            addCriterion("CompensateType <", value, "compensatetype");
            return (Criteria) this;
        }

        public Criteria andCompensatetypeLessThanOrEqualTo(Integer value) {
            addCriterion("CompensateType <=", value, "compensatetype");
            return (Criteria) this;
        }

        public Criteria andCompensatetypeIn(List<Integer> values) {
            addCriterion("CompensateType in", values, "compensatetype");
            return (Criteria) this;
        }

        public Criteria andCompensatetypeNotIn(List<Integer> values) {
            addCriterion("CompensateType not in", values, "compensatetype");
            return (Criteria) this;
        }

        public Criteria andCompensatetypeBetween(Integer value1, Integer value2) {
            addCriterion("CompensateType between", value1, value2, "compensatetype");
            return (Criteria) this;
        }

        public Criteria andCompensatetypeNotBetween(Integer value1, Integer value2) {
            addCriterion("CompensateType not between", value1, value2, "compensatetype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated do_not_delete_during_merge Wed May 18 18:13:37 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}