package com.ymatou.payment.infrastructure.db.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PaymentCheckExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    public PaymentCheckExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPaymentCheckIdIsNull() {
            addCriterion("PaymentCheckId is null");
            return (Criteria) this;
        }

        public Criteria andPaymentCheckIdIsNotNull() {
            addCriterion("PaymentCheckId is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentCheckIdEqualTo(Integer value) {
            addCriterion("PaymentCheckId =", value, "paymentCheckId");
            return (Criteria) this;
        }

        public Criteria andPaymentCheckIdNotEqualTo(Integer value) {
            addCriterion("PaymentCheckId <>", value, "paymentCheckId");
            return (Criteria) this;
        }

        public Criteria andPaymentCheckIdGreaterThan(Integer value) {
            addCriterion("PaymentCheckId >", value, "paymentCheckId");
            return (Criteria) this;
        }

        public Criteria andPaymentCheckIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PaymentCheckId >=", value, "paymentCheckId");
            return (Criteria) this;
        }

        public Criteria andPaymentCheckIdLessThan(Integer value) {
            addCriterion("PaymentCheckId <", value, "paymentCheckId");
            return (Criteria) this;
        }

        public Criteria andPaymentCheckIdLessThanOrEqualTo(Integer value) {
            addCriterion("PaymentCheckId <=", value, "paymentCheckId");
            return (Criteria) this;
        }

        public Criteria andPaymentCheckIdIn(List<Integer> values) {
            addCriterion("PaymentCheckId in", values, "paymentCheckId");
            return (Criteria) this;
        }

        public Criteria andPaymentCheckIdNotIn(List<Integer> values) {
            addCriterion("PaymentCheckId not in", values, "paymentCheckId");
            return (Criteria) this;
        }

        public Criteria andPaymentCheckIdBetween(Integer value1, Integer value2) {
            addCriterion("PaymentCheckId between", value1, value2, "paymentCheckId");
            return (Criteria) this;
        }

        public Criteria andPaymentCheckIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PaymentCheckId not between", value1, value2, "paymentCheckId");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelIsNull() {
            addCriterion("PaymentChannel is null");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelIsNotNull() {
            addCriterion("PaymentChannel is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelEqualTo(Integer value) {
            addCriterion("PaymentChannel =", value, "paymentChannel");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelNotEqualTo(Integer value) {
            addCriterion("PaymentChannel <>", value, "paymentChannel");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelGreaterThan(Integer value) {
            addCriterion("PaymentChannel >", value, "paymentChannel");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelGreaterThanOrEqualTo(Integer value) {
            addCriterion("PaymentChannel >=", value, "paymentChannel");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelLessThan(Integer value) {
            addCriterion("PaymentChannel <", value, "paymentChannel");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelLessThanOrEqualTo(Integer value) {
            addCriterion("PaymentChannel <=", value, "paymentChannel");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelIn(List<Integer> values) {
            addCriterion("PaymentChannel in", values, "paymentChannel");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelNotIn(List<Integer> values) {
            addCriterion("PaymentChannel not in", values, "paymentChannel");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelBetween(Integer value1, Integer value2) {
            addCriterion("PaymentChannel between", value1, value2, "paymentChannel");
            return (Criteria) this;
        }

        public Criteria andPaymentChannelNotBetween(Integer value1, Integer value2) {
            addCriterion("PaymentChannel not between", value1, value2, "paymentChannel");
            return (Criteria) this;
        }

        public Criteria andUploadTimeIsNull() {
            addCriterion("UploadTime is null");
            return (Criteria) this;
        }

        public Criteria andUploadTimeIsNotNull() {
            addCriterion("UploadTime is not null");
            return (Criteria) this;
        }

        public Criteria andUploadTimeEqualTo(Date value) {
            addCriterion("UploadTime =", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeNotEqualTo(Date value) {
            addCriterion("UploadTime <>", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeGreaterThan(Date value) {
            addCriterion("UploadTime >", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UploadTime >=", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeLessThan(Date value) {
            addCriterion("UploadTime <", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeLessThanOrEqualTo(Date value) {
            addCriterion("UploadTime <=", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeIn(List<Date> values) {
            addCriterion("UploadTime in", values, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeNotIn(List<Date> values) {
            addCriterion("UploadTime not in", values, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeBetween(Date value1, Date value2) {
            addCriterion("UploadTime between", value1, value2, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeNotBetween(Date value1, Date value2) {
            addCriterion("UploadTime not between", value1, value2, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadFileIsNull() {
            addCriterion("UploadFile is null");
            return (Criteria) this;
        }

        public Criteria andUploadFileIsNotNull() {
            addCriterion("UploadFile is not null");
            return (Criteria) this;
        }

        public Criteria andUploadFileEqualTo(String value) {
            addCriterion("UploadFile =", value, "uploadFile");
            return (Criteria) this;
        }

        public Criteria andUploadFileNotEqualTo(String value) {
            addCriterion("UploadFile <>", value, "uploadFile");
            return (Criteria) this;
        }

        public Criteria andUploadFileGreaterThan(String value) {
            addCriterion("UploadFile >", value, "uploadFile");
            return (Criteria) this;
        }

        public Criteria andUploadFileGreaterThanOrEqualTo(String value) {
            addCriterion("UploadFile >=", value, "uploadFile");
            return (Criteria) this;
        }

        public Criteria andUploadFileLessThan(String value) {
            addCriterion("UploadFile <", value, "uploadFile");
            return (Criteria) this;
        }

        public Criteria andUploadFileLessThanOrEqualTo(String value) {
            addCriterion("UploadFile <=", value, "uploadFile");
            return (Criteria) this;
        }

        public Criteria andUploadFileLike(String value) {
            addCriterion("UploadFile like", value, "uploadFile");
            return (Criteria) this;
        }

        public Criteria andUploadFileNotLike(String value) {
            addCriterion("UploadFile not like", value, "uploadFile");
            return (Criteria) this;
        }

        public Criteria andUploadFileIn(List<String> values) {
            addCriterion("UploadFile in", values, "uploadFile");
            return (Criteria) this;
        }

        public Criteria andUploadFileNotIn(List<String> values) {
            addCriterion("UploadFile not in", values, "uploadFile");
            return (Criteria) this;
        }

        public Criteria andUploadFileBetween(String value1, String value2) {
            addCriterion("UploadFile between", value1, value2, "uploadFile");
            return (Criteria) this;
        }

        public Criteria andUploadFileNotBetween(String value1, String value2) {
            addCriterion("UploadFile not between", value1, value2, "uploadFile");
            return (Criteria) this;
        }

        public Criteria andOriginalFileNameIsNull() {
            addCriterion("OriginalFileName is null");
            return (Criteria) this;
        }

        public Criteria andOriginalFileNameIsNotNull() {
            addCriterion("OriginalFileName is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalFileNameEqualTo(String value) {
            addCriterion("OriginalFileName =", value, "originalFileName");
            return (Criteria) this;
        }

        public Criteria andOriginalFileNameNotEqualTo(String value) {
            addCriterion("OriginalFileName <>", value, "originalFileName");
            return (Criteria) this;
        }

        public Criteria andOriginalFileNameGreaterThan(String value) {
            addCriterion("OriginalFileName >", value, "originalFileName");
            return (Criteria) this;
        }

        public Criteria andOriginalFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("OriginalFileName >=", value, "originalFileName");
            return (Criteria) this;
        }

        public Criteria andOriginalFileNameLessThan(String value) {
            addCriterion("OriginalFileName <", value, "originalFileName");
            return (Criteria) this;
        }

        public Criteria andOriginalFileNameLessThanOrEqualTo(String value) {
            addCriterion("OriginalFileName <=", value, "originalFileName");
            return (Criteria) this;
        }

        public Criteria andOriginalFileNameLike(String value) {
            addCriterion("OriginalFileName like", value, "originalFileName");
            return (Criteria) this;
        }

        public Criteria andOriginalFileNameNotLike(String value) {
            addCriterion("OriginalFileName not like", value, "originalFileName");
            return (Criteria) this;
        }

        public Criteria andOriginalFileNameIn(List<String> values) {
            addCriterion("OriginalFileName in", values, "originalFileName");
            return (Criteria) this;
        }

        public Criteria andOriginalFileNameNotIn(List<String> values) {
            addCriterion("OriginalFileName not in", values, "originalFileName");
            return (Criteria) this;
        }

        public Criteria andOriginalFileNameBetween(String value1, String value2) {
            addCriterion("OriginalFileName between", value1, value2, "originalFileName");
            return (Criteria) this;
        }

        public Criteria andOriginalFileNameNotBetween(String value1, String value2) {
            addCriterion("OriginalFileName not between", value1, value2, "originalFileName");
            return (Criteria) this;
        }

        public Criteria andYmtPayNumIsNull() {
            addCriterion("YmtPayNum is null");
            return (Criteria) this;
        }

        public Criteria andYmtPayNumIsNotNull() {
            addCriterion("YmtPayNum is not null");
            return (Criteria) this;
        }

        public Criteria andYmtPayNumEqualTo(Integer value) {
            addCriterion("YmtPayNum =", value, "ymtPayNum");
            return (Criteria) this;
        }

        public Criteria andYmtPayNumNotEqualTo(Integer value) {
            addCriterion("YmtPayNum <>", value, "ymtPayNum");
            return (Criteria) this;
        }

        public Criteria andYmtPayNumGreaterThan(Integer value) {
            addCriterion("YmtPayNum >", value, "ymtPayNum");
            return (Criteria) this;
        }

        public Criteria andYmtPayNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("YmtPayNum >=", value, "ymtPayNum");
            return (Criteria) this;
        }

        public Criteria andYmtPayNumLessThan(Integer value) {
            addCriterion("YmtPayNum <", value, "ymtPayNum");
            return (Criteria) this;
        }

        public Criteria andYmtPayNumLessThanOrEqualTo(Integer value) {
            addCriterion("YmtPayNum <=", value, "ymtPayNum");
            return (Criteria) this;
        }

        public Criteria andYmtPayNumIn(List<Integer> values) {
            addCriterion("YmtPayNum in", values, "ymtPayNum");
            return (Criteria) this;
        }

        public Criteria andYmtPayNumNotIn(List<Integer> values) {
            addCriterion("YmtPayNum not in", values, "ymtPayNum");
            return (Criteria) this;
        }

        public Criteria andYmtPayNumBetween(Integer value1, Integer value2) {
            addCriterion("YmtPayNum between", value1, value2, "ymtPayNum");
            return (Criteria) this;
        }

        public Criteria andYmtPayNumNotBetween(Integer value1, Integer value2) {
            addCriterion("YmtPayNum not between", value1, value2, "ymtPayNum");
            return (Criteria) this;
        }

        public Criteria andTrdPayNumIsNull() {
            addCriterion("TrdPayNum is null");
            return (Criteria) this;
        }

        public Criteria andTrdPayNumIsNotNull() {
            addCriterion("TrdPayNum is not null");
            return (Criteria) this;
        }

        public Criteria andTrdPayNumEqualTo(Integer value) {
            addCriterion("TrdPayNum =", value, "trdPayNum");
            return (Criteria) this;
        }

        public Criteria andTrdPayNumNotEqualTo(Integer value) {
            addCriterion("TrdPayNum <>", value, "trdPayNum");
            return (Criteria) this;
        }

        public Criteria andTrdPayNumGreaterThan(Integer value) {
            addCriterion("TrdPayNum >", value, "trdPayNum");
            return (Criteria) this;
        }

        public Criteria andTrdPayNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("TrdPayNum >=", value, "trdPayNum");
            return (Criteria) this;
        }

        public Criteria andTrdPayNumLessThan(Integer value) {
            addCriterion("TrdPayNum <", value, "trdPayNum");
            return (Criteria) this;
        }

        public Criteria andTrdPayNumLessThanOrEqualTo(Integer value) {
            addCriterion("TrdPayNum <=", value, "trdPayNum");
            return (Criteria) this;
        }

        public Criteria andTrdPayNumIn(List<Integer> values) {
            addCriterion("TrdPayNum in", values, "trdPayNum");
            return (Criteria) this;
        }

        public Criteria andTrdPayNumNotIn(List<Integer> values) {
            addCriterion("TrdPayNum not in", values, "trdPayNum");
            return (Criteria) this;
        }

        public Criteria andTrdPayNumBetween(Integer value1, Integer value2) {
            addCriterion("TrdPayNum between", value1, value2, "trdPayNum");
            return (Criteria) this;
        }

        public Criteria andTrdPayNumNotBetween(Integer value1, Integer value2) {
            addCriterion("TrdPayNum not between", value1, value2, "trdPayNum");
            return (Criteria) this;
        }

        public Criteria andYmtPayAmountIsNull() {
            addCriterion("YmtPayAmount is null");
            return (Criteria) this;
        }

        public Criteria andYmtPayAmountIsNotNull() {
            addCriterion("YmtPayAmount is not null");
            return (Criteria) this;
        }

        public Criteria andYmtPayAmountEqualTo(BigDecimal value) {
            addCriterion("YmtPayAmount =", value, "ymtPayAmount");
            return (Criteria) this;
        }

        public Criteria andYmtPayAmountNotEqualTo(BigDecimal value) {
            addCriterion("YmtPayAmount <>", value, "ymtPayAmount");
            return (Criteria) this;
        }

        public Criteria andYmtPayAmountGreaterThan(BigDecimal value) {
            addCriterion("YmtPayAmount >", value, "ymtPayAmount");
            return (Criteria) this;
        }

        public Criteria andYmtPayAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("YmtPayAmount >=", value, "ymtPayAmount");
            return (Criteria) this;
        }

        public Criteria andYmtPayAmountLessThan(BigDecimal value) {
            addCriterion("YmtPayAmount <", value, "ymtPayAmount");
            return (Criteria) this;
        }

        public Criteria andYmtPayAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("YmtPayAmount <=", value, "ymtPayAmount");
            return (Criteria) this;
        }

        public Criteria andYmtPayAmountIn(List<BigDecimal> values) {
            addCriterion("YmtPayAmount in", values, "ymtPayAmount");
            return (Criteria) this;
        }

        public Criteria andYmtPayAmountNotIn(List<BigDecimal> values) {
            addCriterion("YmtPayAmount not in", values, "ymtPayAmount");
            return (Criteria) this;
        }

        public Criteria andYmtPayAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YmtPayAmount between", value1, value2, "ymtPayAmount");
            return (Criteria) this;
        }

        public Criteria andYmtPayAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YmtPayAmount not between", value1, value2, "ymtPayAmount");
            return (Criteria) this;
        }

        public Criteria andTrdPayAmountIsNull() {
            addCriterion("TrdPayAmount is null");
            return (Criteria) this;
        }

        public Criteria andTrdPayAmountIsNotNull() {
            addCriterion("TrdPayAmount is not null");
            return (Criteria) this;
        }

        public Criteria andTrdPayAmountEqualTo(BigDecimal value) {
            addCriterion("TrdPayAmount =", value, "trdPayAmount");
            return (Criteria) this;
        }

        public Criteria andTrdPayAmountNotEqualTo(BigDecimal value) {
            addCriterion("TrdPayAmount <>", value, "trdPayAmount");
            return (Criteria) this;
        }

        public Criteria andTrdPayAmountGreaterThan(BigDecimal value) {
            addCriterion("TrdPayAmount >", value, "trdPayAmount");
            return (Criteria) this;
        }

        public Criteria andTrdPayAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TrdPayAmount >=", value, "trdPayAmount");
            return (Criteria) this;
        }

        public Criteria andTrdPayAmountLessThan(BigDecimal value) {
            addCriterion("TrdPayAmount <", value, "trdPayAmount");
            return (Criteria) this;
        }

        public Criteria andTrdPayAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TrdPayAmount <=", value, "trdPayAmount");
            return (Criteria) this;
        }

        public Criteria andTrdPayAmountIn(List<BigDecimal> values) {
            addCriterion("TrdPayAmount in", values, "trdPayAmount");
            return (Criteria) this;
        }

        public Criteria andTrdPayAmountNotIn(List<BigDecimal> values) {
            addCriterion("TrdPayAmount not in", values, "trdPayAmount");
            return (Criteria) this;
        }

        public Criteria andTrdPayAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TrdPayAmount between", value1, value2, "trdPayAmount");
            return (Criteria) this;
        }

        public Criteria andTrdPayAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TrdPayAmount not between", value1, value2, "trdPayAmount");
            return (Criteria) this;
        }

        public Criteria andFinishTimeIsNull() {
            addCriterion("FinishTime is null");
            return (Criteria) this;
        }

        public Criteria andFinishTimeIsNotNull() {
            addCriterion("FinishTime is not null");
            return (Criteria) this;
        }

        public Criteria andFinishTimeEqualTo(Date value) {
            addCriterion("FinishTime =", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeNotEqualTo(Date value) {
            addCriterion("FinishTime <>", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeGreaterThan(Date value) {
            addCriterion("FinishTime >", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FinishTime >=", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeLessThan(Date value) {
            addCriterion("FinishTime <", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeLessThanOrEqualTo(Date value) {
            addCriterion("FinishTime <=", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeIn(List<Date> values) {
            addCriterion("FinishTime in", values, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeNotIn(List<Date> values) {
            addCriterion("FinishTime not in", values, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeBetween(Date value1, Date value2) {
            addCriterion("FinishTime between", value1, value2, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeNotBetween(Date value1, Date value2) {
            addCriterion("FinishTime not between", value1, value2, "finishTime");
            return (Criteria) this;
        }

        public Criteria andCheckStatusIsNull() {
            addCriterion("CheckStatus is null");
            return (Criteria) this;
        }

        public Criteria andCheckStatusIsNotNull() {
            addCriterion("CheckStatus is not null");
            return (Criteria) this;
        }

        public Criteria andCheckStatusEqualTo(Integer value) {
            addCriterion("CheckStatus =", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusNotEqualTo(Integer value) {
            addCriterion("CheckStatus <>", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusGreaterThan(Integer value) {
            addCriterion("CheckStatus >", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("CheckStatus >=", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusLessThan(Integer value) {
            addCriterion("CheckStatus <", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusLessThanOrEqualTo(Integer value) {
            addCriterion("CheckStatus <=", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusIn(List<Integer> values) {
            addCriterion("CheckStatus in", values, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusNotIn(List<Integer> values) {
            addCriterion("CheckStatus not in", values, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusBetween(Integer value1, Integer value2) {
            addCriterion("CheckStatus between", value1, value2, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("CheckStatus not between", value1, value2, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckAccountIsNull() {
            addCriterion("CheckAccount is null");
            return (Criteria) this;
        }

        public Criteria andCheckAccountIsNotNull() {
            addCriterion("CheckAccount is not null");
            return (Criteria) this;
        }

        public Criteria andCheckAccountEqualTo(String value) {
            addCriterion("CheckAccount =", value, "checkAccount");
            return (Criteria) this;
        }

        public Criteria andCheckAccountNotEqualTo(String value) {
            addCriterion("CheckAccount <>", value, "checkAccount");
            return (Criteria) this;
        }

        public Criteria andCheckAccountGreaterThan(String value) {
            addCriterion("CheckAccount >", value, "checkAccount");
            return (Criteria) this;
        }

        public Criteria andCheckAccountGreaterThanOrEqualTo(String value) {
            addCriterion("CheckAccount >=", value, "checkAccount");
            return (Criteria) this;
        }

        public Criteria andCheckAccountLessThan(String value) {
            addCriterion("CheckAccount <", value, "checkAccount");
            return (Criteria) this;
        }

        public Criteria andCheckAccountLessThanOrEqualTo(String value) {
            addCriterion("CheckAccount <=", value, "checkAccount");
            return (Criteria) this;
        }

        public Criteria andCheckAccountLike(String value) {
            addCriterion("CheckAccount like", value, "checkAccount");
            return (Criteria) this;
        }

        public Criteria andCheckAccountNotLike(String value) {
            addCriterion("CheckAccount not like", value, "checkAccount");
            return (Criteria) this;
        }

        public Criteria andCheckAccountIn(List<String> values) {
            addCriterion("CheckAccount in", values, "checkAccount");
            return (Criteria) this;
        }

        public Criteria andCheckAccountNotIn(List<String> values) {
            addCriterion("CheckAccount not in", values, "checkAccount");
            return (Criteria) this;
        }

        public Criteria andCheckAccountBetween(String value1, String value2) {
            addCriterion("CheckAccount between", value1, value2, "checkAccount");
            return (Criteria) this;
        }

        public Criteria andCheckAccountNotBetween(String value1, String value2) {
            addCriterion("CheckAccount not between", value1, value2, "checkAccount");
            return (Criteria) this;
        }

        public Criteria andServerIpIsNull() {
            addCriterion("ServerIp is null");
            return (Criteria) this;
        }

        public Criteria andServerIpIsNotNull() {
            addCriterion("ServerIp is not null");
            return (Criteria) this;
        }

        public Criteria andServerIpEqualTo(String value) {
            addCriterion("ServerIp =", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotEqualTo(String value) {
            addCriterion("ServerIp <>", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpGreaterThan(String value) {
            addCriterion("ServerIp >", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpGreaterThanOrEqualTo(String value) {
            addCriterion("ServerIp >=", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpLessThan(String value) {
            addCriterion("ServerIp <", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpLessThanOrEqualTo(String value) {
            addCriterion("ServerIp <=", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpLike(String value) {
            addCriterion("ServerIp like", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotLike(String value) {
            addCriterion("ServerIp not like", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpIn(List<String> values) {
            addCriterion("ServerIp in", values, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotIn(List<String> values) {
            addCriterion("ServerIp not in", values, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpBetween(String value1, String value2) {
            addCriterion("ServerIp between", value1, value2, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotBetween(String value1, String value2) {
            addCriterion("ServerIp not between", value1, value2, "serverIp");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("Remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("Remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("Remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("Remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("Remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("Remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("Remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("Remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("Remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("Remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("Remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("Remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("Remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("Remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andYmtDiscountAmountIsNull() {
            addCriterion("YmtDiscountAmount is null");
            return (Criteria) this;
        }

        public Criteria andYmtDiscountAmountIsNotNull() {
            addCriterion("YmtDiscountAmount is not null");
            return (Criteria) this;
        }

        public Criteria andYmtDiscountAmountEqualTo(BigDecimal value) {
            addCriterion("YmtDiscountAmount =", value, "ymtDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andYmtDiscountAmountNotEqualTo(BigDecimal value) {
            addCriterion("YmtDiscountAmount <>", value, "ymtDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andYmtDiscountAmountGreaterThan(BigDecimal value) {
            addCriterion("YmtDiscountAmount >", value, "ymtDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andYmtDiscountAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("YmtDiscountAmount >=", value, "ymtDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andYmtDiscountAmountLessThan(BigDecimal value) {
            addCriterion("YmtDiscountAmount <", value, "ymtDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andYmtDiscountAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("YmtDiscountAmount <=", value, "ymtDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andYmtDiscountAmountIn(List<BigDecimal> values) {
            addCriterion("YmtDiscountAmount in", values, "ymtDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andYmtDiscountAmountNotIn(List<BigDecimal> values) {
            addCriterion("YmtDiscountAmount not in", values, "ymtDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andYmtDiscountAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YmtDiscountAmount between", value1, value2, "ymtDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andYmtDiscountAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YmtDiscountAmount not between", value1, value2, "ymtDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andTrdDiscountAmountIsNull() {
            addCriterion("TrdDiscountAmount is null");
            return (Criteria) this;
        }

        public Criteria andTrdDiscountAmountIsNotNull() {
            addCriterion("TrdDiscountAmount is not null");
            return (Criteria) this;
        }

        public Criteria andTrdDiscountAmountEqualTo(BigDecimal value) {
            addCriterion("TrdDiscountAmount =", value, "trdDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andTrdDiscountAmountNotEqualTo(BigDecimal value) {
            addCriterion("TrdDiscountAmount <>", value, "trdDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andTrdDiscountAmountGreaterThan(BigDecimal value) {
            addCriterion("TrdDiscountAmount >", value, "trdDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andTrdDiscountAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TrdDiscountAmount >=", value, "trdDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andTrdDiscountAmountLessThan(BigDecimal value) {
            addCriterion("TrdDiscountAmount <", value, "trdDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andTrdDiscountAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TrdDiscountAmount <=", value, "trdDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andTrdDiscountAmountIn(List<BigDecimal> values) {
            addCriterion("TrdDiscountAmount in", values, "trdDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andTrdDiscountAmountNotIn(List<BigDecimal> values) {
            addCriterion("TrdDiscountAmount not in", values, "trdDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andTrdDiscountAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TrdDiscountAmount between", value1, value2, "trdDiscountAmount");
            return (Criteria) this;
        }

        public Criteria andTrdDiscountAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TrdDiscountAmount not between", value1, value2, "trdDiscountAmount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated do_not_delete_during_merge Mon Feb 27 18:24:23 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}