package com.ymatou.payment.infrastructure.db.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PaymentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public PaymentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPaymentIdIsNull() {
            addCriterion("PaymentId is null");
            return (Criteria) this;
        }

        public Criteria andPaymentIdIsNotNull() {
            addCriterion("PaymentId is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentIdEqualTo(String value) {
            addCriterion("PaymentId =", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdNotEqualTo(String value) {
            addCriterion("PaymentId <>", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdGreaterThan(String value) {
            addCriterion("PaymentId >", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdGreaterThanOrEqualTo(String value) {
            addCriterion("PaymentId >=", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdLessThan(String value) {
            addCriterion("PaymentId <", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdLessThanOrEqualTo(String value) {
            addCriterion("PaymentId <=", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdLike(String value) {
            addCriterion("PaymentId like", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdNotLike(String value) {
            addCriterion("PaymentId not like", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdIn(List<String> values) {
            addCriterion("PaymentId in", values, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdNotIn(List<String> values) {
            addCriterion("PaymentId not in", values, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdBetween(String value1, String value2) {
            addCriterion("PaymentId between", value1, value2, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdNotBetween(String value1, String value2) {
            addCriterion("PaymentId not between", value1, value2, "paymentId");
            return (Criteria) this;
        }

        public Criteria andBussinessOrderIdIsNull() {
            addCriterion("BussinessOrderId is null");
            return (Criteria) this;
        }

        public Criteria andBussinessOrderIdIsNotNull() {
            addCriterion("BussinessOrderId is not null");
            return (Criteria) this;
        }

        public Criteria andBussinessOrderIdEqualTo(String value) {
            addCriterion("BussinessOrderId =", value, "bussinessOrderId");
            return (Criteria) this;
        }

        public Criteria andBussinessOrderIdNotEqualTo(String value) {
            addCriterion("BussinessOrderId <>", value, "bussinessOrderId");
            return (Criteria) this;
        }

        public Criteria andBussinessOrderIdGreaterThan(String value) {
            addCriterion("BussinessOrderId >", value, "bussinessOrderId");
            return (Criteria) this;
        }

        public Criteria andBussinessOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("BussinessOrderId >=", value, "bussinessOrderId");
            return (Criteria) this;
        }

        public Criteria andBussinessOrderIdLessThan(String value) {
            addCriterion("BussinessOrderId <", value, "bussinessOrderId");
            return (Criteria) this;
        }

        public Criteria andBussinessOrderIdLessThanOrEqualTo(String value) {
            addCriterion("BussinessOrderId <=", value, "bussinessOrderId");
            return (Criteria) this;
        }

        public Criteria andBussinessOrderIdLike(String value) {
            addCriterion("BussinessOrderId like", value, "bussinessOrderId");
            return (Criteria) this;
        }

        public Criteria andBussinessOrderIdNotLike(String value) {
            addCriterion("BussinessOrderId not like", value, "bussinessOrderId");
            return (Criteria) this;
        }

        public Criteria andBussinessOrderIdIn(List<String> values) {
            addCriterion("BussinessOrderId in", values, "bussinessOrderId");
            return (Criteria) this;
        }

        public Criteria andBussinessOrderIdNotIn(List<String> values) {
            addCriterion("BussinessOrderId not in", values, "bussinessOrderId");
            return (Criteria) this;
        }

        public Criteria andBussinessOrderIdBetween(String value1, String value2) {
            addCriterion("BussinessOrderId between", value1, value2, "bussinessOrderId");
            return (Criteria) this;
        }

        public Criteria andBussinessOrderIdNotBetween(String value1, String value2) {
            addCriterion("BussinessOrderId not between", value1, value2, "bussinessOrderId");
            return (Criteria) this;
        }

        public Criteria andInstitutionPaymentIdIsNull() {
            addCriterion("InstitutionPaymentId is null");
            return (Criteria) this;
        }

        public Criteria andInstitutionPaymentIdIsNotNull() {
            addCriterion("InstitutionPaymentId is not null");
            return (Criteria) this;
        }

        public Criteria andInstitutionPaymentIdEqualTo(String value) {
            addCriterion("InstitutionPaymentId =", value, "institutionPaymentId");
            return (Criteria) this;
        }

        public Criteria andInstitutionPaymentIdNotEqualTo(String value) {
            addCriterion("InstitutionPaymentId <>", value, "institutionPaymentId");
            return (Criteria) this;
        }

        public Criteria andInstitutionPaymentIdGreaterThan(String value) {
            addCriterion("InstitutionPaymentId >", value, "institutionPaymentId");
            return (Criteria) this;
        }

        public Criteria andInstitutionPaymentIdGreaterThanOrEqualTo(String value) {
            addCriterion("InstitutionPaymentId >=", value, "institutionPaymentId");
            return (Criteria) this;
        }

        public Criteria andInstitutionPaymentIdLessThan(String value) {
            addCriterion("InstitutionPaymentId <", value, "institutionPaymentId");
            return (Criteria) this;
        }

        public Criteria andInstitutionPaymentIdLessThanOrEqualTo(String value) {
            addCriterion("InstitutionPaymentId <=", value, "institutionPaymentId");
            return (Criteria) this;
        }

        public Criteria andInstitutionPaymentIdLike(String value) {
            addCriterion("InstitutionPaymentId like", value, "institutionPaymentId");
            return (Criteria) this;
        }

        public Criteria andInstitutionPaymentIdNotLike(String value) {
            addCriterion("InstitutionPaymentId not like", value, "institutionPaymentId");
            return (Criteria) this;
        }

        public Criteria andInstitutionPaymentIdIn(List<String> values) {
            addCriterion("InstitutionPaymentId in", values, "institutionPaymentId");
            return (Criteria) this;
        }

        public Criteria andInstitutionPaymentIdNotIn(List<String> values) {
            addCriterion("InstitutionPaymentId not in", values, "institutionPaymentId");
            return (Criteria) this;
        }

        public Criteria andInstitutionPaymentIdBetween(String value1, String value2) {
            addCriterion("InstitutionPaymentId between", value1, value2, "institutionPaymentId");
            return (Criteria) this;
        }

        public Criteria andInstitutionPaymentIdNotBetween(String value1, String value2) {
            addCriterion("InstitutionPaymentId not between", value1, value2, "institutionPaymentId");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNull() {
            addCriterion("PayType is null");
            return (Criteria) this;
        }

        public Criteria andPayTypeIsNotNull() {
            addCriterion("PayType is not null");
            return (Criteria) this;
        }

        public Criteria andPayTypeEqualTo(String value) {
            addCriterion("PayType =", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotEqualTo(String value) {
            addCriterion("PayType <>", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThan(String value) {
            addCriterion("PayType >", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PayType >=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThan(String value) {
            addCriterion("PayType <", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLessThanOrEqualTo(String value) {
            addCriterion("PayType <=", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeLike(String value) {
            addCriterion("PayType like", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotLike(String value) {
            addCriterion("PayType not like", value, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeIn(List<String> values) {
            addCriterion("PayType in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotIn(List<String> values) {
            addCriterion("PayType not in", values, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeBetween(String value1, String value2) {
            addCriterion("PayType between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andPayTypeNotBetween(String value1, String value2) {
            addCriterion("PayType not between", value1, value2, "payType");
            return (Criteria) this;
        }

        public Criteria andPayPriceIsNull() {
            addCriterion("PayPrice is null");
            return (Criteria) this;
        }

        public Criteria andPayPriceIsNotNull() {
            addCriterion("PayPrice is not null");
            return (Criteria) this;
        }

        public Criteria andPayPriceEqualTo(BigDecimal value) {
            addCriterion("PayPrice =", value, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceNotEqualTo(BigDecimal value) {
            addCriterion("PayPrice <>", value, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceGreaterThan(BigDecimal value) {
            addCriterion("PayPrice >", value, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PayPrice >=", value, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceLessThan(BigDecimal value) {
            addCriterion("PayPrice <", value, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PayPrice <=", value, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceIn(List<BigDecimal> values) {
            addCriterion("PayPrice in", values, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceNotIn(List<BigDecimal> values) {
            addCriterion("PayPrice not in", values, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PayPrice between", value1, value2, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PayPrice not between", value1, value2, "payPrice");
            return (Criteria) this;
        }

        public Criteria andActualPayPriceIsNull() {
            addCriterion("ActualPayPrice is null");
            return (Criteria) this;
        }

        public Criteria andActualPayPriceIsNotNull() {
            addCriterion("ActualPayPrice is not null");
            return (Criteria) this;
        }

        public Criteria andActualPayPriceEqualTo(BigDecimal value) {
            addCriterion("ActualPayPrice =", value, "actualPayPrice");
            return (Criteria) this;
        }

        public Criteria andActualPayPriceNotEqualTo(BigDecimal value) {
            addCriterion("ActualPayPrice <>", value, "actualPayPrice");
            return (Criteria) this;
        }

        public Criteria andActualPayPriceGreaterThan(BigDecimal value) {
            addCriterion("ActualPayPrice >", value, "actualPayPrice");
            return (Criteria) this;
        }

        public Criteria andActualPayPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ActualPayPrice >=", value, "actualPayPrice");
            return (Criteria) this;
        }

        public Criteria andActualPayPriceLessThan(BigDecimal value) {
            addCriterion("ActualPayPrice <", value, "actualPayPrice");
            return (Criteria) this;
        }

        public Criteria andActualPayPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ActualPayPrice <=", value, "actualPayPrice");
            return (Criteria) this;
        }

        public Criteria andActualPayPriceIn(List<BigDecimal> values) {
            addCriterion("ActualPayPrice in", values, "actualPayPrice");
            return (Criteria) this;
        }

        public Criteria andActualPayPriceNotIn(List<BigDecimal> values) {
            addCriterion("ActualPayPrice not in", values, "actualPayPrice");
            return (Criteria) this;
        }

        public Criteria andActualPayPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ActualPayPrice between", value1, value2, "actualPayPrice");
            return (Criteria) this;
        }

        public Criteria andActualPayPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ActualPayPrice not between", value1, value2, "actualPayPrice");
            return (Criteria) this;
        }

        public Criteria andPayCurrencyTypeIsNull() {
            addCriterion("PayCurrencyType is null");
            return (Criteria) this;
        }

        public Criteria andPayCurrencyTypeIsNotNull() {
            addCriterion("PayCurrencyType is not null");
            return (Criteria) this;
        }

        public Criteria andPayCurrencyTypeEqualTo(String value) {
            addCriterion("PayCurrencyType =", value, "payCurrencyType");
            return (Criteria) this;
        }

        public Criteria andPayCurrencyTypeNotEqualTo(String value) {
            addCriterion("PayCurrencyType <>", value, "payCurrencyType");
            return (Criteria) this;
        }

        public Criteria andPayCurrencyTypeGreaterThan(String value) {
            addCriterion("PayCurrencyType >", value, "payCurrencyType");
            return (Criteria) this;
        }

        public Criteria andPayCurrencyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PayCurrencyType >=", value, "payCurrencyType");
            return (Criteria) this;
        }

        public Criteria andPayCurrencyTypeLessThan(String value) {
            addCriterion("PayCurrencyType <", value, "payCurrencyType");
            return (Criteria) this;
        }

        public Criteria andPayCurrencyTypeLessThanOrEqualTo(String value) {
            addCriterion("PayCurrencyType <=", value, "payCurrencyType");
            return (Criteria) this;
        }

        public Criteria andPayCurrencyTypeLike(String value) {
            addCriterion("PayCurrencyType like", value, "payCurrencyType");
            return (Criteria) this;
        }

        public Criteria andPayCurrencyTypeNotLike(String value) {
            addCriterion("PayCurrencyType not like", value, "payCurrencyType");
            return (Criteria) this;
        }

        public Criteria andPayCurrencyTypeIn(List<String> values) {
            addCriterion("PayCurrencyType in", values, "payCurrencyType");
            return (Criteria) this;
        }

        public Criteria andPayCurrencyTypeNotIn(List<String> values) {
            addCriterion("PayCurrencyType not in", values, "payCurrencyType");
            return (Criteria) this;
        }

        public Criteria andPayCurrencyTypeBetween(String value1, String value2) {
            addCriterion("PayCurrencyType between", value1, value2, "payCurrencyType");
            return (Criteria) this;
        }

        public Criteria andPayCurrencyTypeNotBetween(String value1, String value2) {
            addCriterion("PayCurrencyType not between", value1, value2, "payCurrencyType");
            return (Criteria) this;
        }

        public Criteria andActualPayCurrencyTypeIsNull() {
            addCriterion("ActualPayCurrencyType is null");
            return (Criteria) this;
        }

        public Criteria andActualPayCurrencyTypeIsNotNull() {
            addCriterion("ActualPayCurrencyType is not null");
            return (Criteria) this;
        }

        public Criteria andActualPayCurrencyTypeEqualTo(String value) {
            addCriterion("ActualPayCurrencyType =", value, "actualPayCurrencyType");
            return (Criteria) this;
        }

        public Criteria andActualPayCurrencyTypeNotEqualTo(String value) {
            addCriterion("ActualPayCurrencyType <>", value, "actualPayCurrencyType");
            return (Criteria) this;
        }

        public Criteria andActualPayCurrencyTypeGreaterThan(String value) {
            addCriterion("ActualPayCurrencyType >", value, "actualPayCurrencyType");
            return (Criteria) this;
        }

        public Criteria andActualPayCurrencyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ActualPayCurrencyType >=", value, "actualPayCurrencyType");
            return (Criteria) this;
        }

        public Criteria andActualPayCurrencyTypeLessThan(String value) {
            addCriterion("ActualPayCurrencyType <", value, "actualPayCurrencyType");
            return (Criteria) this;
        }

        public Criteria andActualPayCurrencyTypeLessThanOrEqualTo(String value) {
            addCriterion("ActualPayCurrencyType <=", value, "actualPayCurrencyType");
            return (Criteria) this;
        }

        public Criteria andActualPayCurrencyTypeLike(String value) {
            addCriterion("ActualPayCurrencyType like", value, "actualPayCurrencyType");
            return (Criteria) this;
        }

        public Criteria andActualPayCurrencyTypeNotLike(String value) {
            addCriterion("ActualPayCurrencyType not like", value, "actualPayCurrencyType");
            return (Criteria) this;
        }

        public Criteria andActualPayCurrencyTypeIn(List<String> values) {
            addCriterion("ActualPayCurrencyType in", values, "actualPayCurrencyType");
            return (Criteria) this;
        }

        public Criteria andActualPayCurrencyTypeNotIn(List<String> values) {
            addCriterion("ActualPayCurrencyType not in", values, "actualPayCurrencyType");
            return (Criteria) this;
        }

        public Criteria andActualPayCurrencyTypeBetween(String value1, String value2) {
            addCriterion("ActualPayCurrencyType between", value1, value2, "actualPayCurrencyType");
            return (Criteria) this;
        }

        public Criteria andActualPayCurrencyTypeNotBetween(String value1, String value2) {
            addCriterion("ActualPayCurrencyType not between", value1, value2, "actualPayCurrencyType");
            return (Criteria) this;
        }

        public Criteria andExchangeRateIsNull() {
            addCriterion("ExchangeRate is null");
            return (Criteria) this;
        }

        public Criteria andExchangeRateIsNotNull() {
            addCriterion("ExchangeRate is not null");
            return (Criteria) this;
        }

        public Criteria andExchangeRateEqualTo(Double value) {
            addCriterion("ExchangeRate =", value, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateNotEqualTo(Double value) {
            addCriterion("ExchangeRate <>", value, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateGreaterThan(Double value) {
            addCriterion("ExchangeRate >", value, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateGreaterThanOrEqualTo(Double value) {
            addCriterion("ExchangeRate >=", value, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateLessThan(Double value) {
            addCriterion("ExchangeRate <", value, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateLessThanOrEqualTo(Double value) {
            addCriterion("ExchangeRate <=", value, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateIn(List<Double> values) {
            addCriterion("ExchangeRate in", values, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateNotIn(List<Double> values) {
            addCriterion("ExchangeRate not in", values, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateBetween(Double value1, Double value2) {
            addCriterion("ExchangeRate between", value1, value2, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateNotBetween(Double value1, Double value2) {
            addCriterion("ExchangeRate not between", value1, value2, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNull() {
            addCriterion("BankId is null");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNotNull() {
            addCriterion("BankId is not null");
            return (Criteria) this;
        }

        public Criteria andBankIdEqualTo(String value) {
            addCriterion("BankId =", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotEqualTo(String value) {
            addCriterion("BankId <>", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThan(String value) {
            addCriterion("BankId >", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThanOrEqualTo(String value) {
            addCriterion("BankId >=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThan(String value) {
            addCriterion("BankId <", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThanOrEqualTo(String value) {
            addCriterion("BankId <=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLike(String value) {
            addCriterion("BankId like", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotLike(String value) {
            addCriterion("BankId not like", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdIn(List<String> values) {
            addCriterion("BankId in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotIn(List<String> values) {
            addCriterion("BankId not in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdBetween(String value1, String value2) {
            addCriterion("BankId between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotBetween(String value1, String value2) {
            addCriterion("BankId not between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNull() {
            addCriterion("CardType is null");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNotNull() {
            addCriterion("CardType is not null");
            return (Criteria) this;
        }

        public Criteria andCardTypeEqualTo(Integer value) {
            addCriterion("CardType =", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotEqualTo(Integer value) {
            addCriterion("CardType <>", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThan(Integer value) {
            addCriterion("CardType >", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("CardType >=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThan(Integer value) {
            addCriterion("CardType <", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThanOrEqualTo(Integer value) {
            addCriterion("CardType <=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeIn(List<Integer> values) {
            addCriterion("CardType in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotIn(List<Integer> values) {
            addCriterion("CardType not in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeBetween(Integer value1, Integer value2) {
            addCriterion("CardType between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("CardType not between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andPayerIdIsNull() {
            addCriterion("PayerId is null");
            return (Criteria) this;
        }

        public Criteria andPayerIdIsNotNull() {
            addCriterion("PayerId is not null");
            return (Criteria) this;
        }

        public Criteria andPayerIdEqualTo(String value) {
            addCriterion("PayerId =", value, "payerId");
            return (Criteria) this;
        }

        public Criteria andPayerIdNotEqualTo(String value) {
            addCriterion("PayerId <>", value, "payerId");
            return (Criteria) this;
        }

        public Criteria andPayerIdGreaterThan(String value) {
            addCriterion("PayerId >", value, "payerId");
            return (Criteria) this;
        }

        public Criteria andPayerIdGreaterThanOrEqualTo(String value) {
            addCriterion("PayerId >=", value, "payerId");
            return (Criteria) this;
        }

        public Criteria andPayerIdLessThan(String value) {
            addCriterion("PayerId <", value, "payerId");
            return (Criteria) this;
        }

        public Criteria andPayerIdLessThanOrEqualTo(String value) {
            addCriterion("PayerId <=", value, "payerId");
            return (Criteria) this;
        }

        public Criteria andPayerIdLike(String value) {
            addCriterion("PayerId like", value, "payerId");
            return (Criteria) this;
        }

        public Criteria andPayerIdNotLike(String value) {
            addCriterion("PayerId not like", value, "payerId");
            return (Criteria) this;
        }

        public Criteria andPayerIdIn(List<String> values) {
            addCriterion("PayerId in", values, "payerId");
            return (Criteria) this;
        }

        public Criteria andPayerIdNotIn(List<String> values) {
            addCriterion("PayerId not in", values, "payerId");
            return (Criteria) this;
        }

        public Criteria andPayerIdBetween(String value1, String value2) {
            addCriterion("PayerId between", value1, value2, "payerId");
            return (Criteria) this;
        }

        public Criteria andPayerIdNotBetween(String value1, String value2) {
            addCriterion("PayerId not between", value1, value2, "payerId");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("CreatedTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("CreatedTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("CreatedTime =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("CreatedTime <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("CreatedTime >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreatedTime >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("CreatedTime <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("CreatedTime <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("CreatedTime in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("CreatedTime not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("CreatedTime between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("CreatedTime not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andPayStatusIsNull() {
            addCriterion("PayStatus is null");
            return (Criteria) this;
        }

        public Criteria andPayStatusIsNotNull() {
            addCriterion("PayStatus is not null");
            return (Criteria) this;
        }

        public Criteria andPayStatusEqualTo(Integer value) {
            addCriterion("PayStatus =", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotEqualTo(Integer value) {
            addCriterion("PayStatus <>", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusGreaterThan(Integer value) {
            addCriterion("PayStatus >", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("PayStatus >=", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLessThan(Integer value) {
            addCriterion("PayStatus <", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLessThanOrEqualTo(Integer value) {
            addCriterion("PayStatus <=", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusIn(List<Integer> values) {
            addCriterion("PayStatus in", values, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotIn(List<Integer> values) {
            addCriterion("PayStatus not in", values, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusBetween(Integer value1, Integer value2) {
            addCriterion("PayStatus between", value1, value2, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("PayStatus not between", value1, value2, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNull() {
            addCriterion("PayTime is null");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNotNull() {
            addCriterion("PayTime is not null");
            return (Criteria) this;
        }

        public Criteria andPayTimeEqualTo(Date value) {
            addCriterion("PayTime =", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotEqualTo(Date value) {
            addCriterion("PayTime <>", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThan(Date value) {
            addCriterion("PayTime >", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PayTime >=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThan(Date value) {
            addCriterion("PayTime <", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThanOrEqualTo(Date value) {
            addCriterion("PayTime <=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeIn(List<Date> values) {
            addCriterion("PayTime in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotIn(List<Date> values) {
            addCriterion("PayTime not in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeBetween(Date value1, Date value2) {
            addCriterion("PayTime between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotBetween(Date value1, Date value2) {
            addCriterion("PayTime not between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeIsNull() {
            addCriterion("LastUpdatedTime is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeIsNotNull() {
            addCriterion("LastUpdatedTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeEqualTo(Date value) {
            addCriterion("LastUpdatedTime =", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeNotEqualTo(Date value) {
            addCriterion("LastUpdatedTime <>", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeGreaterThan(Date value) {
            addCriterion("LastUpdatedTime >", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LastUpdatedTime >=", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeLessThan(Date value) {
            addCriterion("LastUpdatedTime <", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("LastUpdatedTime <=", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeIn(List<Date> values) {
            addCriterion("LastUpdatedTime in", values, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeNotIn(List<Date> values) {
            addCriterion("LastUpdatedTime not in", values, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeBetween(Date value1, Date value2) {
            addCriterion("LastUpdatedTime between", value1, value2, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("LastUpdatedTime not between", value1, value2, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andCheckStatusIsNull() {
            addCriterion("CheckStatus is null");
            return (Criteria) this;
        }

        public Criteria andCheckStatusIsNotNull() {
            addCriterion("CheckStatus is not null");
            return (Criteria) this;
        }

        public Criteria andCheckStatusEqualTo(Integer value) {
            addCriterion("CheckStatus =", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusNotEqualTo(Integer value) {
            addCriterion("CheckStatus <>", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusGreaterThan(Integer value) {
            addCriterion("CheckStatus >", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("CheckStatus >=", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusLessThan(Integer value) {
            addCriterion("CheckStatus <", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusLessThanOrEqualTo(Integer value) {
            addCriterion("CheckStatus <=", value, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusIn(List<Integer> values) {
            addCriterion("CheckStatus in", values, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusNotIn(List<Integer> values) {
            addCriterion("CheckStatus not in", values, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusBetween(Integer value1, Integer value2) {
            addCriterion("CheckStatus between", value1, value2, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andCheckStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("CheckStatus not between", value1, value2, "checkStatus");
            return (Criteria) this;
        }

        public Criteria andRefundAmtIsNull() {
            addCriterion("RefundAmt is null");
            return (Criteria) this;
        }

        public Criteria andRefundAmtIsNotNull() {
            addCriterion("RefundAmt is not null");
            return (Criteria) this;
        }

        public Criteria andRefundAmtEqualTo(BigDecimal value) {
            addCriterion("RefundAmt =", value, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtNotEqualTo(BigDecimal value) {
            addCriterion("RefundAmt <>", value, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtGreaterThan(BigDecimal value) {
            addCriterion("RefundAmt >", value, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RefundAmt >=", value, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtLessThan(BigDecimal value) {
            addCriterion("RefundAmt <", value, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RefundAmt <=", value, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtIn(List<BigDecimal> values) {
            addCriterion("RefundAmt in", values, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtNotIn(List<BigDecimal> values) {
            addCriterion("RefundAmt not in", values, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RefundAmt between", value1, value2, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RefundAmt not between", value1, value2, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andCompletedRefundAmtIsNull() {
            addCriterion("CompletedRefundAmt is null");
            return (Criteria) this;
        }

        public Criteria andCompletedRefundAmtIsNotNull() {
            addCriterion("CompletedRefundAmt is not null");
            return (Criteria) this;
        }

        public Criteria andCompletedRefundAmtEqualTo(BigDecimal value) {
            addCriterion("CompletedRefundAmt =", value, "completedRefundAmt");
            return (Criteria) this;
        }

        public Criteria andCompletedRefundAmtNotEqualTo(BigDecimal value) {
            addCriterion("CompletedRefundAmt <>", value, "completedRefundAmt");
            return (Criteria) this;
        }

        public Criteria andCompletedRefundAmtGreaterThan(BigDecimal value) {
            addCriterion("CompletedRefundAmt >", value, "completedRefundAmt");
            return (Criteria) this;
        }

        public Criteria andCompletedRefundAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CompletedRefundAmt >=", value, "completedRefundAmt");
            return (Criteria) this;
        }

        public Criteria andCompletedRefundAmtLessThan(BigDecimal value) {
            addCriterion("CompletedRefundAmt <", value, "completedRefundAmt");
            return (Criteria) this;
        }

        public Criteria andCompletedRefundAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CompletedRefundAmt <=", value, "completedRefundAmt");
            return (Criteria) this;
        }

        public Criteria andCompletedRefundAmtIn(List<BigDecimal> values) {
            addCriterion("CompletedRefundAmt in", values, "completedRefundAmt");
            return (Criteria) this;
        }

        public Criteria andCompletedRefundAmtNotIn(List<BigDecimal> values) {
            addCriterion("CompletedRefundAmt not in", values, "completedRefundAmt");
            return (Criteria) this;
        }

        public Criteria andCompletedRefundAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CompletedRefundAmt between", value1, value2, "completedRefundAmt");
            return (Criteria) this;
        }

        public Criteria andCompletedRefundAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CompletedRefundAmt not between", value1, value2, "completedRefundAmt");
            return (Criteria) this;
        }

        public Criteria andRetryCountIsNull() {
            addCriterion("RetryCount is null");
            return (Criteria) this;
        }

        public Criteria andRetryCountIsNotNull() {
            addCriterion("RetryCount is not null");
            return (Criteria) this;
        }

        public Criteria andRetryCountEqualTo(Integer value) {
            addCriterion("RetryCount =", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountNotEqualTo(Integer value) {
            addCriterion("RetryCount <>", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountGreaterThan(Integer value) {
            addCriterion("RetryCount >", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("RetryCount >=", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountLessThan(Integer value) {
            addCriterion("RetryCount <", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountLessThanOrEqualTo(Integer value) {
            addCriterion("RetryCount <=", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountIn(List<Integer> values) {
            addCriterion("RetryCount in", values, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountNotIn(List<Integer> values) {
            addCriterion("RetryCount not in", values, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountBetween(Integer value1, Integer value2) {
            addCriterion("RetryCount between", value1, value2, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountNotBetween(Integer value1, Integer value2) {
            addCriterion("RetryCount not between", value1, value2, "retryCount");
            return (Criteria) this;
        }

        public Criteria andNotifyStatusIsNull() {
            addCriterion("NotifyStatus is null");
            return (Criteria) this;
        }

        public Criteria andNotifyStatusIsNotNull() {
            addCriterion("NotifyStatus is not null");
            return (Criteria) this;
        }

        public Criteria andNotifyStatusEqualTo(Integer value) {
            addCriterion("NotifyStatus =", value, "notifyStatus");
            return (Criteria) this;
        }

        public Criteria andNotifyStatusNotEqualTo(Integer value) {
            addCriterion("NotifyStatus <>", value, "notifyStatus");
            return (Criteria) this;
        }

        public Criteria andNotifyStatusGreaterThan(Integer value) {
            addCriterion("NotifyStatus >", value, "notifyStatus");
            return (Criteria) this;
        }

        public Criteria andNotifyStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("NotifyStatus >=", value, "notifyStatus");
            return (Criteria) this;
        }

        public Criteria andNotifyStatusLessThan(Integer value) {
            addCriterion("NotifyStatus <", value, "notifyStatus");
            return (Criteria) this;
        }

        public Criteria andNotifyStatusLessThanOrEqualTo(Integer value) {
            addCriterion("NotifyStatus <=", value, "notifyStatus");
            return (Criteria) this;
        }

        public Criteria andNotifyStatusIn(List<Integer> values) {
            addCriterion("NotifyStatus in", values, "notifyStatus");
            return (Criteria) this;
        }

        public Criteria andNotifyStatusNotIn(List<Integer> values) {
            addCriterion("NotifyStatus not in", values, "notifyStatus");
            return (Criteria) this;
        }

        public Criteria andNotifyStatusBetween(Integer value1, Integer value2) {
            addCriterion("NotifyStatus between", value1, value2, "notifyStatus");
            return (Criteria) this;
        }

        public Criteria andNotifyStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("NotifyStatus not between", value1, value2, "notifyStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PP_Payment
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 13 13:47:39 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}