package com.ymatou.payment.infrastructure.db.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PaymentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    public PaymentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPaymentidIsNull() {
            addCriterion("PaymentId is null");
            return (Criteria) this;
        }

        public Criteria andPaymentidIsNotNull() {
            addCriterion("PaymentId is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentidEqualTo(String value) {
            addCriterion("PaymentId =", value, "paymentid");
            return (Criteria) this;
        }

        public Criteria andPaymentidNotEqualTo(String value) {
            addCriterion("PaymentId <>", value, "paymentid");
            return (Criteria) this;
        }

        public Criteria andPaymentidGreaterThan(String value) {
            addCriterion("PaymentId >", value, "paymentid");
            return (Criteria) this;
        }

        public Criteria andPaymentidGreaterThanOrEqualTo(String value) {
            addCriterion("PaymentId >=", value, "paymentid");
            return (Criteria) this;
        }

        public Criteria andPaymentidLessThan(String value) {
            addCriterion("PaymentId <", value, "paymentid");
            return (Criteria) this;
        }

        public Criteria andPaymentidLessThanOrEqualTo(String value) {
            addCriterion("PaymentId <=", value, "paymentid");
            return (Criteria) this;
        }

        public Criteria andPaymentidLike(String value) {
            addCriterion("PaymentId like", value, "paymentid");
            return (Criteria) this;
        }

        public Criteria andPaymentidNotLike(String value) {
            addCriterion("PaymentId not like", value, "paymentid");
            return (Criteria) this;
        }

        public Criteria andPaymentidIn(List<String> values) {
            addCriterion("PaymentId in", values, "paymentid");
            return (Criteria) this;
        }

        public Criteria andPaymentidNotIn(List<String> values) {
            addCriterion("PaymentId not in", values, "paymentid");
            return (Criteria) this;
        }

        public Criteria andPaymentidBetween(String value1, String value2) {
            addCriterion("PaymentId between", value1, value2, "paymentid");
            return (Criteria) this;
        }

        public Criteria andPaymentidNotBetween(String value1, String value2) {
            addCriterion("PaymentId not between", value1, value2, "paymentid");
            return (Criteria) this;
        }

        public Criteria andBussinessorderidIsNull() {
            addCriterion("BussinessOrderId is null");
            return (Criteria) this;
        }

        public Criteria andBussinessorderidIsNotNull() {
            addCriterion("BussinessOrderId is not null");
            return (Criteria) this;
        }

        public Criteria andBussinessorderidEqualTo(String value) {
            addCriterion("BussinessOrderId =", value, "bussinessorderid");
            return (Criteria) this;
        }

        public Criteria andBussinessorderidNotEqualTo(String value) {
            addCriterion("BussinessOrderId <>", value, "bussinessorderid");
            return (Criteria) this;
        }

        public Criteria andBussinessorderidGreaterThan(String value) {
            addCriterion("BussinessOrderId >", value, "bussinessorderid");
            return (Criteria) this;
        }

        public Criteria andBussinessorderidGreaterThanOrEqualTo(String value) {
            addCriterion("BussinessOrderId >=", value, "bussinessorderid");
            return (Criteria) this;
        }

        public Criteria andBussinessorderidLessThan(String value) {
            addCriterion("BussinessOrderId <", value, "bussinessorderid");
            return (Criteria) this;
        }

        public Criteria andBussinessorderidLessThanOrEqualTo(String value) {
            addCriterion("BussinessOrderId <=", value, "bussinessorderid");
            return (Criteria) this;
        }

        public Criteria andBussinessorderidLike(String value) {
            addCriterion("BussinessOrderId like", value, "bussinessorderid");
            return (Criteria) this;
        }

        public Criteria andBussinessorderidNotLike(String value) {
            addCriterion("BussinessOrderId not like", value, "bussinessorderid");
            return (Criteria) this;
        }

        public Criteria andBussinessorderidIn(List<String> values) {
            addCriterion("BussinessOrderId in", values, "bussinessorderid");
            return (Criteria) this;
        }

        public Criteria andBussinessorderidNotIn(List<String> values) {
            addCriterion("BussinessOrderId not in", values, "bussinessorderid");
            return (Criteria) this;
        }

        public Criteria andBussinessorderidBetween(String value1, String value2) {
            addCriterion("BussinessOrderId between", value1, value2, "bussinessorderid");
            return (Criteria) this;
        }

        public Criteria andBussinessorderidNotBetween(String value1, String value2) {
            addCriterion("BussinessOrderId not between", value1, value2, "bussinessorderid");
            return (Criteria) this;
        }

        public Criteria andInstitutionpaymentidIsNull() {
            addCriterion("InstitutionPaymentId is null");
            return (Criteria) this;
        }

        public Criteria andInstitutionpaymentidIsNotNull() {
            addCriterion("InstitutionPaymentId is not null");
            return (Criteria) this;
        }

        public Criteria andInstitutionpaymentidEqualTo(String value) {
            addCriterion("InstitutionPaymentId =", value, "institutionpaymentid");
            return (Criteria) this;
        }

        public Criteria andInstitutionpaymentidNotEqualTo(String value) {
            addCriterion("InstitutionPaymentId <>", value, "institutionpaymentid");
            return (Criteria) this;
        }

        public Criteria andInstitutionpaymentidGreaterThan(String value) {
            addCriterion("InstitutionPaymentId >", value, "institutionpaymentid");
            return (Criteria) this;
        }

        public Criteria andInstitutionpaymentidGreaterThanOrEqualTo(String value) {
            addCriterion("InstitutionPaymentId >=", value, "institutionpaymentid");
            return (Criteria) this;
        }

        public Criteria andInstitutionpaymentidLessThan(String value) {
            addCriterion("InstitutionPaymentId <", value, "institutionpaymentid");
            return (Criteria) this;
        }

        public Criteria andInstitutionpaymentidLessThanOrEqualTo(String value) {
            addCriterion("InstitutionPaymentId <=", value, "institutionpaymentid");
            return (Criteria) this;
        }

        public Criteria andInstitutionpaymentidLike(String value) {
            addCriterion("InstitutionPaymentId like", value, "institutionpaymentid");
            return (Criteria) this;
        }

        public Criteria andInstitutionpaymentidNotLike(String value) {
            addCriterion("InstitutionPaymentId not like", value, "institutionpaymentid");
            return (Criteria) this;
        }

        public Criteria andInstitutionpaymentidIn(List<String> values) {
            addCriterion("InstitutionPaymentId in", values, "institutionpaymentid");
            return (Criteria) this;
        }

        public Criteria andInstitutionpaymentidNotIn(List<String> values) {
            addCriterion("InstitutionPaymentId not in", values, "institutionpaymentid");
            return (Criteria) this;
        }

        public Criteria andInstitutionpaymentidBetween(String value1, String value2) {
            addCriterion("InstitutionPaymentId between", value1, value2, "institutionpaymentid");
            return (Criteria) this;
        }

        public Criteria andInstitutionpaymentidNotBetween(String value1, String value2) {
            addCriterion("InstitutionPaymentId not between", value1, value2, "institutionpaymentid");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNull() {
            addCriterion("PayType is null");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNotNull() {
            addCriterion("PayType is not null");
            return (Criteria) this;
        }

        public Criteria andPaytypeEqualTo(String value) {
            addCriterion("PayType =", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotEqualTo(String value) {
            addCriterion("PayType <>", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThan(String value) {
            addCriterion("PayType >", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThanOrEqualTo(String value) {
            addCriterion("PayType >=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThan(String value) {
            addCriterion("PayType <", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThanOrEqualTo(String value) {
            addCriterion("PayType <=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLike(String value) {
            addCriterion("PayType like", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotLike(String value) {
            addCriterion("PayType not like", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeIn(List<String> values) {
            addCriterion("PayType in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotIn(List<String> values) {
            addCriterion("PayType not in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeBetween(String value1, String value2) {
            addCriterion("PayType between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotBetween(String value1, String value2) {
            addCriterion("PayType not between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaypriceIsNull() {
            addCriterion("PayPrice is null");
            return (Criteria) this;
        }

        public Criteria andPaypriceIsNotNull() {
            addCriterion("PayPrice is not null");
            return (Criteria) this;
        }

        public Criteria andPaypriceEqualTo(BigDecimal value) {
            addCriterion("PayPrice =", value, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceNotEqualTo(BigDecimal value) {
            addCriterion("PayPrice <>", value, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceGreaterThan(BigDecimal value) {
            addCriterion("PayPrice >", value, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PayPrice >=", value, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceLessThan(BigDecimal value) {
            addCriterion("PayPrice <", value, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PayPrice <=", value, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceIn(List<BigDecimal> values) {
            addCriterion("PayPrice in", values, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceNotIn(List<BigDecimal> values) {
            addCriterion("PayPrice not in", values, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PayPrice between", value1, value2, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PayPrice not between", value1, value2, "payprice");
            return (Criteria) this;
        }

        public Criteria andActualpaypriceIsNull() {
            addCriterion("ActualPayPrice is null");
            return (Criteria) this;
        }

        public Criteria andActualpaypriceIsNotNull() {
            addCriterion("ActualPayPrice is not null");
            return (Criteria) this;
        }

        public Criteria andActualpaypriceEqualTo(BigDecimal value) {
            addCriterion("ActualPayPrice =", value, "actualpayprice");
            return (Criteria) this;
        }

        public Criteria andActualpaypriceNotEqualTo(BigDecimal value) {
            addCriterion("ActualPayPrice <>", value, "actualpayprice");
            return (Criteria) this;
        }

        public Criteria andActualpaypriceGreaterThan(BigDecimal value) {
            addCriterion("ActualPayPrice >", value, "actualpayprice");
            return (Criteria) this;
        }

        public Criteria andActualpaypriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ActualPayPrice >=", value, "actualpayprice");
            return (Criteria) this;
        }

        public Criteria andActualpaypriceLessThan(BigDecimal value) {
            addCriterion("ActualPayPrice <", value, "actualpayprice");
            return (Criteria) this;
        }

        public Criteria andActualpaypriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ActualPayPrice <=", value, "actualpayprice");
            return (Criteria) this;
        }

        public Criteria andActualpaypriceIn(List<BigDecimal> values) {
            addCriterion("ActualPayPrice in", values, "actualpayprice");
            return (Criteria) this;
        }

        public Criteria andActualpaypriceNotIn(List<BigDecimal> values) {
            addCriterion("ActualPayPrice not in", values, "actualpayprice");
            return (Criteria) this;
        }

        public Criteria andActualpaypriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ActualPayPrice between", value1, value2, "actualpayprice");
            return (Criteria) this;
        }

        public Criteria andActualpaypriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ActualPayPrice not between", value1, value2, "actualpayprice");
            return (Criteria) this;
        }

        public Criteria andPaycurrencytypeIsNull() {
            addCriterion("PayCurrencyType is null");
            return (Criteria) this;
        }

        public Criteria andPaycurrencytypeIsNotNull() {
            addCriterion("PayCurrencyType is not null");
            return (Criteria) this;
        }

        public Criteria andPaycurrencytypeEqualTo(String value) {
            addCriterion("PayCurrencyType =", value, "paycurrencytype");
            return (Criteria) this;
        }

        public Criteria andPaycurrencytypeNotEqualTo(String value) {
            addCriterion("PayCurrencyType <>", value, "paycurrencytype");
            return (Criteria) this;
        }

        public Criteria andPaycurrencytypeGreaterThan(String value) {
            addCriterion("PayCurrencyType >", value, "paycurrencytype");
            return (Criteria) this;
        }

        public Criteria andPaycurrencytypeGreaterThanOrEqualTo(String value) {
            addCriterion("PayCurrencyType >=", value, "paycurrencytype");
            return (Criteria) this;
        }

        public Criteria andPaycurrencytypeLessThan(String value) {
            addCriterion("PayCurrencyType <", value, "paycurrencytype");
            return (Criteria) this;
        }

        public Criteria andPaycurrencytypeLessThanOrEqualTo(String value) {
            addCriterion("PayCurrencyType <=", value, "paycurrencytype");
            return (Criteria) this;
        }

        public Criteria andPaycurrencytypeLike(String value) {
            addCriterion("PayCurrencyType like", value, "paycurrencytype");
            return (Criteria) this;
        }

        public Criteria andPaycurrencytypeNotLike(String value) {
            addCriterion("PayCurrencyType not like", value, "paycurrencytype");
            return (Criteria) this;
        }

        public Criteria andPaycurrencytypeIn(List<String> values) {
            addCriterion("PayCurrencyType in", values, "paycurrencytype");
            return (Criteria) this;
        }

        public Criteria andPaycurrencytypeNotIn(List<String> values) {
            addCriterion("PayCurrencyType not in", values, "paycurrencytype");
            return (Criteria) this;
        }

        public Criteria andPaycurrencytypeBetween(String value1, String value2) {
            addCriterion("PayCurrencyType between", value1, value2, "paycurrencytype");
            return (Criteria) this;
        }

        public Criteria andPaycurrencytypeNotBetween(String value1, String value2) {
            addCriterion("PayCurrencyType not between", value1, value2, "paycurrencytype");
            return (Criteria) this;
        }

        public Criteria andActualpaycurrencytypeIsNull() {
            addCriterion("ActualPayCurrencyType is null");
            return (Criteria) this;
        }

        public Criteria andActualpaycurrencytypeIsNotNull() {
            addCriterion("ActualPayCurrencyType is not null");
            return (Criteria) this;
        }

        public Criteria andActualpaycurrencytypeEqualTo(String value) {
            addCriterion("ActualPayCurrencyType =", value, "actualpaycurrencytype");
            return (Criteria) this;
        }

        public Criteria andActualpaycurrencytypeNotEqualTo(String value) {
            addCriterion("ActualPayCurrencyType <>", value, "actualpaycurrencytype");
            return (Criteria) this;
        }

        public Criteria andActualpaycurrencytypeGreaterThan(String value) {
            addCriterion("ActualPayCurrencyType >", value, "actualpaycurrencytype");
            return (Criteria) this;
        }

        public Criteria andActualpaycurrencytypeGreaterThanOrEqualTo(String value) {
            addCriterion("ActualPayCurrencyType >=", value, "actualpaycurrencytype");
            return (Criteria) this;
        }

        public Criteria andActualpaycurrencytypeLessThan(String value) {
            addCriterion("ActualPayCurrencyType <", value, "actualpaycurrencytype");
            return (Criteria) this;
        }

        public Criteria andActualpaycurrencytypeLessThanOrEqualTo(String value) {
            addCriterion("ActualPayCurrencyType <=", value, "actualpaycurrencytype");
            return (Criteria) this;
        }

        public Criteria andActualpaycurrencytypeLike(String value) {
            addCriterion("ActualPayCurrencyType like", value, "actualpaycurrencytype");
            return (Criteria) this;
        }

        public Criteria andActualpaycurrencytypeNotLike(String value) {
            addCriterion("ActualPayCurrencyType not like", value, "actualpaycurrencytype");
            return (Criteria) this;
        }

        public Criteria andActualpaycurrencytypeIn(List<String> values) {
            addCriterion("ActualPayCurrencyType in", values, "actualpaycurrencytype");
            return (Criteria) this;
        }

        public Criteria andActualpaycurrencytypeNotIn(List<String> values) {
            addCriterion("ActualPayCurrencyType not in", values, "actualpaycurrencytype");
            return (Criteria) this;
        }

        public Criteria andActualpaycurrencytypeBetween(String value1, String value2) {
            addCriterion("ActualPayCurrencyType between", value1, value2, "actualpaycurrencytype");
            return (Criteria) this;
        }

        public Criteria andActualpaycurrencytypeNotBetween(String value1, String value2) {
            addCriterion("ActualPayCurrencyType not between", value1, value2, "actualpaycurrencytype");
            return (Criteria) this;
        }

        public Criteria andExchangerateIsNull() {
            addCriterion("ExchangeRate is null");
            return (Criteria) this;
        }

        public Criteria andExchangerateIsNotNull() {
            addCriterion("ExchangeRate is not null");
            return (Criteria) this;
        }

        public Criteria andExchangerateEqualTo(Double value) {
            addCriterion("ExchangeRate =", value, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateNotEqualTo(Double value) {
            addCriterion("ExchangeRate <>", value, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateGreaterThan(Double value) {
            addCriterion("ExchangeRate >", value, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateGreaterThanOrEqualTo(Double value) {
            addCriterion("ExchangeRate >=", value, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateLessThan(Double value) {
            addCriterion("ExchangeRate <", value, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateLessThanOrEqualTo(Double value) {
            addCriterion("ExchangeRate <=", value, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateIn(List<Double> values) {
            addCriterion("ExchangeRate in", values, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateNotIn(List<Double> values) {
            addCriterion("ExchangeRate not in", values, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateBetween(Double value1, Double value2) {
            addCriterion("ExchangeRate between", value1, value2, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateNotBetween(Double value1, Double value2) {
            addCriterion("ExchangeRate not between", value1, value2, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andBankidIsNull() {
            addCriterion("BankId is null");
            return (Criteria) this;
        }

        public Criteria andBankidIsNotNull() {
            addCriterion("BankId is not null");
            return (Criteria) this;
        }

        public Criteria andBankidEqualTo(String value) {
            addCriterion("BankId =", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidNotEqualTo(String value) {
            addCriterion("BankId <>", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidGreaterThan(String value) {
            addCriterion("BankId >", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidGreaterThanOrEqualTo(String value) {
            addCriterion("BankId >=", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidLessThan(String value) {
            addCriterion("BankId <", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidLessThanOrEqualTo(String value) {
            addCriterion("BankId <=", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidLike(String value) {
            addCriterion("BankId like", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidNotLike(String value) {
            addCriterion("BankId not like", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidIn(List<String> values) {
            addCriterion("BankId in", values, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidNotIn(List<String> values) {
            addCriterion("BankId not in", values, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidBetween(String value1, String value2) {
            addCriterion("BankId between", value1, value2, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidNotBetween(String value1, String value2) {
            addCriterion("BankId not between", value1, value2, "bankid");
            return (Criteria) this;
        }

        public Criteria andCardtypeIsNull() {
            addCriterion("CardType is null");
            return (Criteria) this;
        }

        public Criteria andCardtypeIsNotNull() {
            addCriterion("CardType is not null");
            return (Criteria) this;
        }

        public Criteria andCardtypeEqualTo(Integer value) {
            addCriterion("CardType =", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeNotEqualTo(Integer value) {
            addCriterion("CardType <>", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeGreaterThan(Integer value) {
            addCriterion("CardType >", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("CardType >=", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeLessThan(Integer value) {
            addCriterion("CardType <", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeLessThanOrEqualTo(Integer value) {
            addCriterion("CardType <=", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeIn(List<Integer> values) {
            addCriterion("CardType in", values, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeNotIn(List<Integer> values) {
            addCriterion("CardType not in", values, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeBetween(Integer value1, Integer value2) {
            addCriterion("CardType between", value1, value2, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeNotBetween(Integer value1, Integer value2) {
            addCriterion("CardType not between", value1, value2, "cardtype");
            return (Criteria) this;
        }

        public Criteria andPayeridIsNull() {
            addCriterion("PayerId is null");
            return (Criteria) this;
        }

        public Criteria andPayeridIsNotNull() {
            addCriterion("PayerId is not null");
            return (Criteria) this;
        }

        public Criteria andPayeridEqualTo(String value) {
            addCriterion("PayerId =", value, "payerid");
            return (Criteria) this;
        }

        public Criteria andPayeridNotEqualTo(String value) {
            addCriterion("PayerId <>", value, "payerid");
            return (Criteria) this;
        }

        public Criteria andPayeridGreaterThan(String value) {
            addCriterion("PayerId >", value, "payerid");
            return (Criteria) this;
        }

        public Criteria andPayeridGreaterThanOrEqualTo(String value) {
            addCriterion("PayerId >=", value, "payerid");
            return (Criteria) this;
        }

        public Criteria andPayeridLessThan(String value) {
            addCriterion("PayerId <", value, "payerid");
            return (Criteria) this;
        }

        public Criteria andPayeridLessThanOrEqualTo(String value) {
            addCriterion("PayerId <=", value, "payerid");
            return (Criteria) this;
        }

        public Criteria andPayeridLike(String value) {
            addCriterion("PayerId like", value, "payerid");
            return (Criteria) this;
        }

        public Criteria andPayeridNotLike(String value) {
            addCriterion("PayerId not like", value, "payerid");
            return (Criteria) this;
        }

        public Criteria andPayeridIn(List<String> values) {
            addCriterion("PayerId in", values, "payerid");
            return (Criteria) this;
        }

        public Criteria andPayeridNotIn(List<String> values) {
            addCriterion("PayerId not in", values, "payerid");
            return (Criteria) this;
        }

        public Criteria andPayeridBetween(String value1, String value2) {
            addCriterion("PayerId between", value1, value2, "payerid");
            return (Criteria) this;
        }

        public Criteria andPayeridNotBetween(String value1, String value2) {
            addCriterion("PayerId not between", value1, value2, "payerid");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeIsNull() {
            addCriterion("CreatedTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeIsNotNull() {
            addCriterion("CreatedTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeEqualTo(Date value) {
            addCriterion("CreatedTime =", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeNotEqualTo(Date value) {
            addCriterion("CreatedTime <>", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeGreaterThan(Date value) {
            addCriterion("CreatedTime >", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreatedTime >=", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeLessThan(Date value) {
            addCriterion("CreatedTime <", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeLessThanOrEqualTo(Date value) {
            addCriterion("CreatedTime <=", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeIn(List<Date> values) {
            addCriterion("CreatedTime in", values, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeNotIn(List<Date> values) {
            addCriterion("CreatedTime not in", values, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeBetween(Date value1, Date value2) {
            addCriterion("CreatedTime between", value1, value2, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeNotBetween(Date value1, Date value2) {
            addCriterion("CreatedTime not between", value1, value2, "createdtime");
            return (Criteria) this;
        }

        public Criteria andPaystatusIsNull() {
            addCriterion("PayStatus is null");
            return (Criteria) this;
        }

        public Criteria andPaystatusIsNotNull() {
            addCriterion("PayStatus is not null");
            return (Criteria) this;
        }

        public Criteria andPaystatusEqualTo(Integer value) {
            addCriterion("PayStatus =", value, "paystatus");
            return (Criteria) this;
        }

        public Criteria andPaystatusNotEqualTo(Integer value) {
            addCriterion("PayStatus <>", value, "paystatus");
            return (Criteria) this;
        }

        public Criteria andPaystatusGreaterThan(Integer value) {
            addCriterion("PayStatus >", value, "paystatus");
            return (Criteria) this;
        }

        public Criteria andPaystatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("PayStatus >=", value, "paystatus");
            return (Criteria) this;
        }

        public Criteria andPaystatusLessThan(Integer value) {
            addCriterion("PayStatus <", value, "paystatus");
            return (Criteria) this;
        }

        public Criteria andPaystatusLessThanOrEqualTo(Integer value) {
            addCriterion("PayStatus <=", value, "paystatus");
            return (Criteria) this;
        }

        public Criteria andPaystatusIn(List<Integer> values) {
            addCriterion("PayStatus in", values, "paystatus");
            return (Criteria) this;
        }

        public Criteria andPaystatusNotIn(List<Integer> values) {
            addCriterion("PayStatus not in", values, "paystatus");
            return (Criteria) this;
        }

        public Criteria andPaystatusBetween(Integer value1, Integer value2) {
            addCriterion("PayStatus between", value1, value2, "paystatus");
            return (Criteria) this;
        }

        public Criteria andPaystatusNotBetween(Integer value1, Integer value2) {
            addCriterion("PayStatus not between", value1, value2, "paystatus");
            return (Criteria) this;
        }

        public Criteria andPaytimeIsNull() {
            addCriterion("PayTime is null");
            return (Criteria) this;
        }

        public Criteria andPaytimeIsNotNull() {
            addCriterion("PayTime is not null");
            return (Criteria) this;
        }

        public Criteria andPaytimeEqualTo(Date value) {
            addCriterion("PayTime =", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeNotEqualTo(Date value) {
            addCriterion("PayTime <>", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeGreaterThan(Date value) {
            addCriterion("PayTime >", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PayTime >=", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeLessThan(Date value) {
            addCriterion("PayTime <", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeLessThanOrEqualTo(Date value) {
            addCriterion("PayTime <=", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeIn(List<Date> values) {
            addCriterion("PayTime in", values, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeNotIn(List<Date> values) {
            addCriterion("PayTime not in", values, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeBetween(Date value1, Date value2) {
            addCriterion("PayTime between", value1, value2, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeNotBetween(Date value1, Date value2) {
            addCriterion("PayTime not between", value1, value2, "paytime");
            return (Criteria) this;
        }

        public Criteria andLastupdatedtimeIsNull() {
            addCriterion("LastUpdatedTime is null");
            return (Criteria) this;
        }

        public Criteria andLastupdatedtimeIsNotNull() {
            addCriterion("LastUpdatedTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdatedtimeEqualTo(Date value) {
            addCriterion("LastUpdatedTime =", value, "lastupdatedtime");
            return (Criteria) this;
        }

        public Criteria andLastupdatedtimeNotEqualTo(Date value) {
            addCriterion("LastUpdatedTime <>", value, "lastupdatedtime");
            return (Criteria) this;
        }

        public Criteria andLastupdatedtimeGreaterThan(Date value) {
            addCriterion("LastUpdatedTime >", value, "lastupdatedtime");
            return (Criteria) this;
        }

        public Criteria andLastupdatedtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LastUpdatedTime >=", value, "lastupdatedtime");
            return (Criteria) this;
        }

        public Criteria andLastupdatedtimeLessThan(Date value) {
            addCriterion("LastUpdatedTime <", value, "lastupdatedtime");
            return (Criteria) this;
        }

        public Criteria andLastupdatedtimeLessThanOrEqualTo(Date value) {
            addCriterion("LastUpdatedTime <=", value, "lastupdatedtime");
            return (Criteria) this;
        }

        public Criteria andLastupdatedtimeIn(List<Date> values) {
            addCriterion("LastUpdatedTime in", values, "lastupdatedtime");
            return (Criteria) this;
        }

        public Criteria andLastupdatedtimeNotIn(List<Date> values) {
            addCriterion("LastUpdatedTime not in", values, "lastupdatedtime");
            return (Criteria) this;
        }

        public Criteria andLastupdatedtimeBetween(Date value1, Date value2) {
            addCriterion("LastUpdatedTime between", value1, value2, "lastupdatedtime");
            return (Criteria) this;
        }

        public Criteria andLastupdatedtimeNotBetween(Date value1, Date value2) {
            addCriterion("LastUpdatedTime not between", value1, value2, "lastupdatedtime");
            return (Criteria) this;
        }

        public Criteria andCheckstatusIsNull() {
            addCriterion("CheckStatus is null");
            return (Criteria) this;
        }

        public Criteria andCheckstatusIsNotNull() {
            addCriterion("CheckStatus is not null");
            return (Criteria) this;
        }

        public Criteria andCheckstatusEqualTo(Integer value) {
            addCriterion("CheckStatus =", value, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusNotEqualTo(Integer value) {
            addCriterion("CheckStatus <>", value, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusGreaterThan(Integer value) {
            addCriterion("CheckStatus >", value, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("CheckStatus >=", value, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusLessThan(Integer value) {
            addCriterion("CheckStatus <", value, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusLessThanOrEqualTo(Integer value) {
            addCriterion("CheckStatus <=", value, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusIn(List<Integer> values) {
            addCriterion("CheckStatus in", values, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusNotIn(List<Integer> values) {
            addCriterion("CheckStatus not in", values, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusBetween(Integer value1, Integer value2) {
            addCriterion("CheckStatus between", value1, value2, "checkstatus");
            return (Criteria) this;
        }

        public Criteria andCheckstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("CheckStatus not between", value1, value2, "checkstatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PP_Payment
     *
     * @mbggenerated do_not_delete_during_merge Wed May 18 16:40:40 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PP_Payment
     *
     * @mbggenerated Wed May 18 16:40:40 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}