package com.ymatou.payment.infrastructure.db.model;

public class PpCompensateprocessinfoWithBLOBs extends CompensateprocessinfoPo {
    /**
     * CLOB(2147483647) 必填<br>
     * 
     */
    private String requestdata;

    /**
     * BINARY(8) 必填<br>
     * 
     */
    private byte[] dataversion;

    /**
     * CLOB(2147483647) 必填<br>
     */
    public String getRequestdata() {
        return requestdata;
    }

    /**
     * CLOB(2147483647) 必填<br>
     */
    public void setRequestdata(String requestdata) {
        this.requestdata = requestdata == null ? null : requestdata.trim();
    }

    /**
     * BINARY(8) 必填<br>
     */
    public byte[] getDataversion() {
        return dataversion;
    }

    /**
     * BINARY(8) 必填<br>
     */
    public void setDataversion(byte[] dataversion) {
        this.dataversion = dataversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 18:13:37 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", requestdata=").append(requestdata);
        sb.append(", dataversion=").append(dataversion);
        sb.append("]");
        return sb.toString();
    }
}