package com.ymatou.payment.infrastructure.db.model;

import java.util.Date;

public class RefundmiscrequestlogPo {
    /**
     * CHAR(36) 默认值[(newid())] 必填<br>
     * 
     */
    private String logid;

    /**
     * VARCHAR(64) 必填<br>
     * 
     */
    private String correlateid;

    /**
     * VARCHAR(64) 必填<br>
     * 
     */
    private String method;

    /**
     * TIMESTAMP(23,3) 默认值[(getdate())] 必填<br>
     * 
     */
    private Date requesttime;

    /**
     * TIMESTAMP(23,3) 必填<br>
     * 
     */
    private Date responsetime;

    /**
     * BIT(1) 默认值[((0))] 必填<br>
     * 
     */
    private Boolean isexception;

    /**
     * VARCHAR(64)<br>
     * 
     */
    private String refundbatchno;

    /**
     * CHAR(36) 默认值[(newid())] 必填<br>
     */
    public String getLogid() {
        return logid;
    }

    /**
     * CHAR(36) 默认值[(newid())] 必填<br>
     */
    public void setLogid(String logid) {
        this.logid = logid == null ? null : logid.trim();
    }

    /**
     * VARCHAR(64) 必填<br>
     */
    public String getCorrelateid() {
        return correlateid;
    }

    /**
     * VARCHAR(64) 必填<br>
     */
    public void setCorrelateid(String correlateid) {
        this.correlateid = correlateid == null ? null : correlateid.trim();
    }

    /**
     * VARCHAR(64) 必填<br>
     */
    public String getMethod() {
        return method;
    }

    /**
     * VARCHAR(64) 必填<br>
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * TIMESTAMP(23,3) 默认值[(getdate())] 必填<br>
     */
    public Date getRequesttime() {
        return requesttime;
    }

    /**
     * TIMESTAMP(23,3) 默认值[(getdate())] 必填<br>
     */
    public void setRequesttime(Date requesttime) {
        this.requesttime = requesttime;
    }

    /**
     * TIMESTAMP(23,3) 必填<br>
     */
    public Date getResponsetime() {
        return responsetime;
    }

    /**
     * TIMESTAMP(23,3) 必填<br>
     */
    public void setResponsetime(Date responsetime) {
        this.responsetime = responsetime;
    }

    /**
     * BIT(1) 默认值[((0))] 必填<br>
     */
    public Boolean getIsexception() {
        return isexception;
    }

    /**
     * BIT(1) 默认值[((0))] 必填<br>
     */
    public void setIsexception(Boolean isexception) {
        this.isexception = isexception;
    }

    /**
     * VARCHAR(64)<br>
     */
    public String getRefundbatchno() {
        return refundbatchno;
    }

    /**
     * VARCHAR(64)<br>
     */
    public void setRefundbatchno(String refundbatchno) {
        this.refundbatchno = refundbatchno == null ? null : refundbatchno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Fri May 20 14:09:31 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logid=").append(logid);
        sb.append(", correlateid=").append(correlateid);
        sb.append(", method=").append(method);
        sb.append(", requesttime=").append(requesttime);
        sb.append(", responsetime=").append(responsetime);
        sb.append(", isexception=").append(isexception);
        sb.append(", refundbatchno=").append(refundbatchno);
        sb.append("]");
        return sb.toString();
    }
}