package com.ymatou.payment.infrastructure.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RefundMiscRequestLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public RefundMiscRequestLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLogIdIsNull() {
            addCriterion("LogId is null");
            return (Criteria) this;
        }

        public Criteria andLogIdIsNotNull() {
            addCriterion("LogId is not null");
            return (Criteria) this;
        }

        public Criteria andLogIdEqualTo(String value) {
            addCriterion("LogId =", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotEqualTo(String value) {
            addCriterion("LogId <>", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdGreaterThan(String value) {
            addCriterion("LogId >", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdGreaterThanOrEqualTo(String value) {
            addCriterion("LogId >=", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLessThan(String value) {
            addCriterion("LogId <", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLessThanOrEqualTo(String value) {
            addCriterion("LogId <=", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLike(String value) {
            addCriterion("LogId like", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotLike(String value) {
            addCriterion("LogId not like", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdIn(List<String> values) {
            addCriterion("LogId in", values, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotIn(List<String> values) {
            addCriterion("LogId not in", values, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdBetween(String value1, String value2) {
            addCriterion("LogId between", value1, value2, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotBetween(String value1, String value2) {
            addCriterion("LogId not between", value1, value2, "logId");
            return (Criteria) this;
        }

        public Criteria andCorrelateIdIsNull() {
            addCriterion("CorrelateId is null");
            return (Criteria) this;
        }

        public Criteria andCorrelateIdIsNotNull() {
            addCriterion("CorrelateId is not null");
            return (Criteria) this;
        }

        public Criteria andCorrelateIdEqualTo(String value) {
            addCriterion("CorrelateId =", value, "correlateId");
            return (Criteria) this;
        }

        public Criteria andCorrelateIdNotEqualTo(String value) {
            addCriterion("CorrelateId <>", value, "correlateId");
            return (Criteria) this;
        }

        public Criteria andCorrelateIdGreaterThan(String value) {
            addCriterion("CorrelateId >", value, "correlateId");
            return (Criteria) this;
        }

        public Criteria andCorrelateIdGreaterThanOrEqualTo(String value) {
            addCriterion("CorrelateId >=", value, "correlateId");
            return (Criteria) this;
        }

        public Criteria andCorrelateIdLessThan(String value) {
            addCriterion("CorrelateId <", value, "correlateId");
            return (Criteria) this;
        }

        public Criteria andCorrelateIdLessThanOrEqualTo(String value) {
            addCriterion("CorrelateId <=", value, "correlateId");
            return (Criteria) this;
        }

        public Criteria andCorrelateIdLike(String value) {
            addCriterion("CorrelateId like", value, "correlateId");
            return (Criteria) this;
        }

        public Criteria andCorrelateIdNotLike(String value) {
            addCriterion("CorrelateId not like", value, "correlateId");
            return (Criteria) this;
        }

        public Criteria andCorrelateIdIn(List<String> values) {
            addCriterion("CorrelateId in", values, "correlateId");
            return (Criteria) this;
        }

        public Criteria andCorrelateIdNotIn(List<String> values) {
            addCriterion("CorrelateId not in", values, "correlateId");
            return (Criteria) this;
        }

        public Criteria andCorrelateIdBetween(String value1, String value2) {
            addCriterion("CorrelateId between", value1, value2, "correlateId");
            return (Criteria) this;
        }

        public Criteria andCorrelateIdNotBetween(String value1, String value2) {
            addCriterion("CorrelateId not between", value1, value2, "correlateId");
            return (Criteria) this;
        }

        public Criteria andMethodIsNull() {
            addCriterion("Method is null");
            return (Criteria) this;
        }

        public Criteria andMethodIsNotNull() {
            addCriterion("Method is not null");
            return (Criteria) this;
        }

        public Criteria andMethodEqualTo(String value) {
            addCriterion("Method =", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotEqualTo(String value) {
            addCriterion("Method <>", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThan(String value) {
            addCriterion("Method >", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThanOrEqualTo(String value) {
            addCriterion("Method >=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThan(String value) {
            addCriterion("Method <", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThanOrEqualTo(String value) {
            addCriterion("Method <=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLike(String value) {
            addCriterion("Method like", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotLike(String value) {
            addCriterion("Method not like", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodIn(List<String> values) {
            addCriterion("Method in", values, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotIn(List<String> values) {
            addCriterion("Method not in", values, "method");
            return (Criteria) this;
        }

        public Criteria andMethodBetween(String value1, String value2) {
            addCriterion("Method between", value1, value2, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotBetween(String value1, String value2) {
            addCriterion("Method not between", value1, value2, "method");
            return (Criteria) this;
        }

        public Criteria andRequestTimeIsNull() {
            addCriterion("RequestTime is null");
            return (Criteria) this;
        }

        public Criteria andRequestTimeIsNotNull() {
            addCriterion("RequestTime is not null");
            return (Criteria) this;
        }

        public Criteria andRequestTimeEqualTo(Date value) {
            addCriterion("RequestTime =", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeNotEqualTo(Date value) {
            addCriterion("RequestTime <>", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeGreaterThan(Date value) {
            addCriterion("RequestTime >", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("RequestTime >=", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeLessThan(Date value) {
            addCriterion("RequestTime <", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeLessThanOrEqualTo(Date value) {
            addCriterion("RequestTime <=", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeIn(List<Date> values) {
            addCriterion("RequestTime in", values, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeNotIn(List<Date> values) {
            addCriterion("RequestTime not in", values, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeBetween(Date value1, Date value2) {
            addCriterion("RequestTime between", value1, value2, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeNotBetween(Date value1, Date value2) {
            addCriterion("RequestTime not between", value1, value2, "requestTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeIsNull() {
            addCriterion("ResponseTime is null");
            return (Criteria) this;
        }

        public Criteria andResponseTimeIsNotNull() {
            addCriterion("ResponseTime is not null");
            return (Criteria) this;
        }

        public Criteria andResponseTimeEqualTo(Date value) {
            addCriterion("ResponseTime =", value, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeNotEqualTo(Date value) {
            addCriterion("ResponseTime <>", value, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeGreaterThan(Date value) {
            addCriterion("ResponseTime >", value, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ResponseTime >=", value, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeLessThan(Date value) {
            addCriterion("ResponseTime <", value, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeLessThanOrEqualTo(Date value) {
            addCriterion("ResponseTime <=", value, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeIn(List<Date> values) {
            addCriterion("ResponseTime in", values, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeNotIn(List<Date> values) {
            addCriterion("ResponseTime not in", values, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeBetween(Date value1, Date value2) {
            addCriterion("ResponseTime between", value1, value2, "responseTime");
            return (Criteria) this;
        }

        public Criteria andResponseTimeNotBetween(Date value1, Date value2) {
            addCriterion("ResponseTime not between", value1, value2, "responseTime");
            return (Criteria) this;
        }

        public Criteria andIsExceptionIsNull() {
            addCriterion("IsException is null");
            return (Criteria) this;
        }

        public Criteria andIsExceptionIsNotNull() {
            addCriterion("IsException is not null");
            return (Criteria) this;
        }

        public Criteria andIsExceptionEqualTo(Boolean value) {
            addCriterion("IsException =", value, "isException");
            return (Criteria) this;
        }

        public Criteria andIsExceptionNotEqualTo(Boolean value) {
            addCriterion("IsException <>", value, "isException");
            return (Criteria) this;
        }

        public Criteria andIsExceptionGreaterThan(Boolean value) {
            addCriterion("IsException >", value, "isException");
            return (Criteria) this;
        }

        public Criteria andIsExceptionGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IsException >=", value, "isException");
            return (Criteria) this;
        }

        public Criteria andIsExceptionLessThan(Boolean value) {
            addCriterion("IsException <", value, "isException");
            return (Criteria) this;
        }

        public Criteria andIsExceptionLessThanOrEqualTo(Boolean value) {
            addCriterion("IsException <=", value, "isException");
            return (Criteria) this;
        }

        public Criteria andIsExceptionIn(List<Boolean> values) {
            addCriterion("IsException in", values, "isException");
            return (Criteria) this;
        }

        public Criteria andIsExceptionNotIn(List<Boolean> values) {
            addCriterion("IsException not in", values, "isException");
            return (Criteria) this;
        }

        public Criteria andIsExceptionBetween(Boolean value1, Boolean value2) {
            addCriterion("IsException between", value1, value2, "isException");
            return (Criteria) this;
        }

        public Criteria andIsExceptionNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IsException not between", value1, value2, "isException");
            return (Criteria) this;
        }

        public Criteria andRefundBatchNoIsNull() {
            addCriterion("RefundBatchNo is null");
            return (Criteria) this;
        }

        public Criteria andRefundBatchNoIsNotNull() {
            addCriterion("RefundBatchNo is not null");
            return (Criteria) this;
        }

        public Criteria andRefundBatchNoEqualTo(String value) {
            addCriterion("RefundBatchNo =", value, "refundBatchNo");
            return (Criteria) this;
        }

        public Criteria andRefundBatchNoNotEqualTo(String value) {
            addCriterion("RefundBatchNo <>", value, "refundBatchNo");
            return (Criteria) this;
        }

        public Criteria andRefundBatchNoGreaterThan(String value) {
            addCriterion("RefundBatchNo >", value, "refundBatchNo");
            return (Criteria) this;
        }

        public Criteria andRefundBatchNoGreaterThanOrEqualTo(String value) {
            addCriterion("RefundBatchNo >=", value, "refundBatchNo");
            return (Criteria) this;
        }

        public Criteria andRefundBatchNoLessThan(String value) {
            addCriterion("RefundBatchNo <", value, "refundBatchNo");
            return (Criteria) this;
        }

        public Criteria andRefundBatchNoLessThanOrEqualTo(String value) {
            addCriterion("RefundBatchNo <=", value, "refundBatchNo");
            return (Criteria) this;
        }

        public Criteria andRefundBatchNoLike(String value) {
            addCriterion("RefundBatchNo like", value, "refundBatchNo");
            return (Criteria) this;
        }

        public Criteria andRefundBatchNoNotLike(String value) {
            addCriterion("RefundBatchNo not like", value, "refundBatchNo");
            return (Criteria) this;
        }

        public Criteria andRefundBatchNoIn(List<String> values) {
            addCriterion("RefundBatchNo in", values, "refundBatchNo");
            return (Criteria) this;
        }

        public Criteria andRefundBatchNoNotIn(List<String> values) {
            addCriterion("RefundBatchNo not in", values, "refundBatchNo");
            return (Criteria) this;
        }

        public Criteria andRefundBatchNoBetween(String value1, String value2) {
            addCriterion("RefundBatchNo between", value1, value2, "refundBatchNo");
            return (Criteria) this;
        }

        public Criteria andRefundBatchNoNotBetween(String value1, String value2) {
            addCriterion("RefundBatchNo not between", value1, value2, "refundBatchNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 13 13:47:39 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Mon Jun 13 13:47:39 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}