package com.ymatou.payment.infrastructure.db.model;

public class RefundmiscrequestlogWithBLOBs extends RefundmiscrequestlogPo {
    /**
     * CLOB(2147483647) 必填<br>
     * 
     */
    private String requestdata;

    /**
     * CLOB(2147483647)<br>
     * 
     */
    private String responsedata;

    /**
     * CLOB(2147483647)<br>
     * 
     */
    private String exceptiondetail;

    /**
     * CLOB(2147483647) 必填<br>
     */
    public String getRequestdata() {
        return requestdata;
    }

    /**
     * CLOB(2147483647) 必填<br>
     */
    public void setRequestdata(String requestdata) {
        this.requestdata = requestdata == null ? null : requestdata.trim();
    }

    /**
     * CLOB(2147483647)<br>
     */
    public String getResponsedata() {
        return responsedata;
    }

    /**
     * CLOB(2147483647)<br>
     */
    public void setResponsedata(String responsedata) {
        this.responsedata = responsedata == null ? null : responsedata.trim();
    }

    /**
     * CLOB(2147483647)<br>
     */
    public String getExceptiondetail() {
        return exceptiondetail;
    }

    /**
     * CLOB(2147483647)<br>
     */
    public void setExceptiondetail(String exceptiondetail) {
        this.exceptiondetail = exceptiondetail == null ? null : exceptiondetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", requestdata=").append(requestdata);
        sb.append(", responsedata=").append(responsedata);
        sb.append(", exceptiondetail=").append(exceptiondetail);
        sb.append("]");
        return sb.toString();
    }
}