package com.ymatou.payment.infrastructure.db.mapper;

import com.ymatou.payment.infrastructure.db.model.AlipaynotifylogExample;
import com.ymatou.payment.infrastructure.db.model.AlipaynotifylogPo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlipaynotifylogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int countByExample(AlipaynotifylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int deleteByExample(AlipaynotifylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int deleteByPrimaryKey(Integer iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int insert(AlipaynotifylogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int insertSelective(AlipaynotifylogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    List<AlipaynotifylogPo> selectByExampleWithBLOBs(AlipaynotifylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    List<AlipaynotifylogPo> selectByExample(AlipaynotifylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    AlipaynotifylogPo selectByPrimaryKey(Integer iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") AlipaynotifylogPo record, @Param("example") AlipaynotifylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") AlipaynotifylogPo record, @Param("example") AlipaynotifylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int updateByExample(@Param("record") AlipaynotifylogPo record, @Param("example") AlipaynotifylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int updateByPrimaryKeySelective(AlipaynotifylogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(AlipaynotifylogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ymt_AlipayNotifyLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int updateByPrimaryKey(AlipaynotifylogPo record);
}