package com.ymatou.payment.infrastructure.db.mapper;

import com.ymatou.payment.infrastructure.db.model.BussinessOrderExample;
import com.ymatou.payment.infrastructure.db.model.BussinessOrderPo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BussinessOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int countByExample(BussinessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int deleteByExample(BussinessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int deleteByPrimaryKey(String bussinessOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int insert(BussinessOrderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int insertSelective(BussinessOrderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    List<BussinessOrderPo> selectByExampleWithBLOBs(BussinessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    List<BussinessOrderPo> selectByExample(BussinessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    BussinessOrderPo selectByPrimaryKey(String bussinessOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int updateByExampleSelective(@Param("record") BussinessOrderPo record, @Param("example") BussinessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") BussinessOrderPo record, @Param("example") BussinessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int updateByExample(@Param("record") BussinessOrderPo record, @Param("example") BussinessOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int updateByPrimaryKeySelective(BussinessOrderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(BussinessOrderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int updateByPrimaryKey(BussinessOrderPo record);
}