package com.ymatou.payment.infrastructure.db.mapper;

import com.ymatou.payment.infrastructure.db.model.BussinessorderExample;
import com.ymatou.payment.infrastructure.db.model.BussinessorderPo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BussinessorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Wed May 04 11:33:50 CST 2016
     */
    int countByExample(BussinessorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Wed May 04 11:33:50 CST 2016
     */
    int deleteByExample(BussinessorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Wed May 04 11:33:50 CST 2016
     */
    int deleteByPrimaryKey(String bussinessorderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Wed May 04 11:33:50 CST 2016
     */
    int insert(BussinessorderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Wed May 04 11:33:50 CST 2016
     */
    int insertSelective(BussinessorderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Wed May 04 11:33:50 CST 2016
     */
    List<BussinessorderPo> selectByExampleWithBLOBs(BussinessorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Wed May 04 11:33:50 CST 2016
     */
    List<BussinessorderPo> selectByExample(BussinessorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Wed May 04 11:33:50 CST 2016
     */
    BussinessorderPo selectByPrimaryKey(String bussinessorderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Wed May 04 11:33:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") BussinessorderPo record, @Param("example") BussinessorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Wed May 04 11:33:50 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") BussinessorderPo record, @Param("example") BussinessorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Wed May 04 11:33:50 CST 2016
     */
    int updateByExample(@Param("record") BussinessorderPo record, @Param("example") BussinessorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Wed May 04 11:33:50 CST 2016
     */
    int updateByPrimaryKeySelective(BussinessorderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Wed May 04 11:33:50 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(BussinessorderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_BussinessOrder
     *
     * @mbggenerated Wed May 04 11:33:50 CST 2016
     */
    int updateByPrimaryKey(BussinessorderPo record);
}