package com.ymatou.payment.infrastructure.db.mapper;

import com.ymatou.payment.infrastructure.db.model.CmbAggrementExample;
import com.ymatou.payment.infrastructure.db.model.CmbAggrementPo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmbAggrementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Tue Nov 15 20:02:34 CST 2016
     */
    int countByExample(CmbAggrementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Tue Nov 15 20:02:34 CST 2016
     */
    int deleteByExample(CmbAggrementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Tue Nov 15 20:02:34 CST 2016
     */
    int deleteByPrimaryKey(Long aggId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Tue Nov 15 20:02:34 CST 2016
     */
    int insert(CmbAggrementPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Tue Nov 15 20:02:34 CST 2016
     */
    int insertSelective(CmbAggrementPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Tue Nov 15 20:02:34 CST 2016
     */
    List<CmbAggrementPo> selectByExample(CmbAggrementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Tue Nov 15 20:02:34 CST 2016
     */
    CmbAggrementPo selectByPrimaryKey(Long aggId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Tue Nov 15 20:02:34 CST 2016
     */
    int updateByExampleSelective(@Param("record") CmbAggrementPo record, @Param("example") CmbAggrementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Tue Nov 15 20:02:34 CST 2016
     */
    int updateByExample(@Param("record") CmbAggrementPo record, @Param("example") CmbAggrementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Tue Nov 15 20:02:34 CST 2016
     */
    int updateByPrimaryKeySelective(CmbAggrementPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbAggrement
     *
     * @mbggenerated Tue Nov 15 20:02:34 CST 2016
     */
    int updateByPrimaryKey(CmbAggrementPo record);
}