package com.ymatou.payment.infrastructure.db.mapper;

import com.ymatou.payment.infrastructure.db.model.CmbPublicKeyExample;
import com.ymatou.payment.infrastructure.db.model.CmbPublicKeyPo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmbPublicKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbPublicKey
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int countByExample(CmbPublicKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbPublicKey
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int deleteByExample(CmbPublicKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbPublicKey
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbPublicKey
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int insert(CmbPublicKeyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbPublicKey
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int insertSelective(CmbPublicKeyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbPublicKey
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    List<CmbPublicKeyPo> selectByExample(CmbPublicKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbPublicKey
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    CmbPublicKeyPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbPublicKey
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmbPublicKeyPo record, @Param("example") CmbPublicKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbPublicKey
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int updateByExample(@Param("record") CmbPublicKeyPo record, @Param("example") CmbPublicKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbPublicKey
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int updateByPrimaryKeySelective(CmbPublicKeyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CmbPublicKey
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int updateByPrimaryKey(CmbPublicKeyPo record);
}