package com.ymatou.payment.infrastructure.db.mapper;

import com.ymatou.payment.infrastructure.db.model.CompensateprocessinfoExample;
import com.ymatou.payment.infrastructure.db.model.CompensateprocessinfoPo;
import com.ymatou.payment.infrastructure.db.model.PpCompensateprocessinfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompensateprocessinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int countByExample(CompensateprocessinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int deleteByExample(CompensateprocessinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int deleteByPrimaryKey(Long compensateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int insert(PpCompensateprocessinfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int insertSelective(PpCompensateprocessinfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    List<PpCompensateprocessinfoWithBLOBs> selectByExampleWithBLOBs(CompensateprocessinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    List<CompensateprocessinfoPo> selectByExample(CompensateprocessinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    PpCompensateprocessinfoWithBLOBs selectByPrimaryKey(Long compensateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int updateByExampleSelective(@Param("record") PpCompensateprocessinfoWithBLOBs record, @Param("example") CompensateprocessinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") PpCompensateprocessinfoWithBLOBs record, @Param("example") CompensateprocessinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int updateByExample(@Param("record") CompensateprocessinfoPo record, @Param("example") CompensateprocessinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int updateByPrimaryKeySelective(PpCompensateprocessinfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(PpCompensateprocessinfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_CompensateProcessInfo
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int updateByPrimaryKey(CompensateprocessinfoPo record);
}