package com.ymatou.payment.infrastructure.db.mapper;

import com.ymatou.payment.infrastructure.db.model.PaymentExample;
import com.ymatou.payment.infrastructure.db.model.PaymentPo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int countByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int deleteByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int deleteByPrimaryKey(String paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int insert(PaymentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int insertSelective(PaymentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    List<PaymentPo> selectByExampleWithBLOBs(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    List<PaymentPo> selectByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    PaymentPo selectByPrimaryKey(String paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int updateByExampleSelective(@Param("record") PaymentPo record, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") PaymentPo record, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int updateByExample(@Param("record") PaymentPo record, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int updateByPrimaryKeySelective(PaymentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(PaymentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_Payment
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int updateByPrimaryKey(PaymentPo record);
}