package com.ymatou.payment.infrastructure.db.mapper;

import com.ymatou.payment.infrastructure.db.model.PaymentParamExample;
import com.ymatou.payment.infrastructure.db.model.PaymentParamPo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentParam
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int countByExample(PaymentParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentParam
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int deleteByExample(PaymentParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentParam
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int deleteByPrimaryKey(Integer paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentParam
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int insert(PaymentParamPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentParam
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int insertSelective(PaymentParamPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentParam
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    List<PaymentParamPo> selectByExample(PaymentParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentParam
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    PaymentParamPo selectByPrimaryKey(Integer paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentParam
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int updateByExampleSelective(@Param("record") PaymentParamPo record, @Param("example") PaymentParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentParam
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int updateByExample(@Param("record") PaymentParamPo record, @Param("example") PaymentParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentParam
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int updateByPrimaryKeySelective(PaymentParamPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentParam
     *
     * @mbggenerated Mon Jun 27 11:23:40 CST 2016
     */
    int updateByPrimaryKey(PaymentParamPo record);
}