package com.ymatou.payment.infrastructure.db.mapper;

import com.ymatou.payment.infrastructure.db.model.PaymentCheckExample;
import com.ymatou.payment.infrastructure.db.model.PaymentCheckPo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int countByExample(PaymentCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int deleteByExample(PaymentCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int deleteByPrimaryKey(Integer paymentCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int insert(PaymentCheckPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int insertSelective(PaymentCheckPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    List<PaymentCheckPo> selectByExample(PaymentCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    PaymentCheckPo selectByPrimaryKey(Integer paymentCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int updateByExampleSelective(@Param("record") PaymentCheckPo record, @Param("example") PaymentCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int updateByExample(@Param("record") PaymentCheckPo record, @Param("example") PaymentCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int updateByPrimaryKeySelective(PaymentCheckPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PP_PaymentCheck
     *
     * @mbggenerated Tue Jan 17 09:37:41 CST 2017
     */
    int updateByPrimaryKey(PaymentCheckPo record);
}