package com.ymatou.payment.infrastructure.db.mapper;

import com.ymatou.payment.infrastructure.db.model.RefundrequestExample;
import com.ymatou.payment.infrastructure.db.model.RefundrequestPo;
import com.ymatou.payment.infrastructure.db.model.RefundrequestWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RefundrequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int countByExample(RefundrequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int deleteByExample(RefundrequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int deleteByPrimaryKey(String paymentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int insert(RefundrequestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int insertSelective(RefundrequestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    List<RefundrequestWithBLOBs> selectByExampleWithBLOBs(RefundrequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    List<RefundrequestPo> selectByExample(RefundrequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    RefundrequestWithBLOBs selectByPrimaryKey(String paymentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int updateByExampleSelective(@Param("record") RefundrequestWithBLOBs record, @Param("example") RefundrequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") RefundrequestWithBLOBs record, @Param("example") RefundrequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int updateByExample(@Param("record") RefundrequestPo record, @Param("example") RefundrequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int updateByPrimaryKeySelective(RefundrequestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(RefundrequestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Wed May 18 17:28:11 CST 2016
     */
    int updateByPrimaryKey(RefundrequestPo record);
}