package com.ymatou.payment.infrastructure.db.mapper;

import com.ymatou.payment.infrastructure.db.model.RefundRequestExample;
import com.ymatou.payment.infrastructure.db.model.RefundRequestPo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RefundRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int countByExample(RefundRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int deleteByExample(RefundRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int deleteByPrimaryKey(Integer refundId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int insert(RefundRequestPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int insertSelective(RefundRequestPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    List<RefundRequestPo> selectByExampleWithBLOBs(RefundRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    List<RefundRequestPo> selectByExample(RefundRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    RefundRequestPo selectByPrimaryKey(Integer refundId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int updateByExampleSelective(@Param("record") RefundRequestPo record, @Param("example") RefundRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") RefundRequestPo record, @Param("example") RefundRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int updateByExample(@Param("record") RefundRequestPo record, @Param("example") RefundRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int updateByPrimaryKeySelective(RefundRequestPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(RefundRequestPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundRequest
     *
     * @mbggenerated Mon Feb 27 18:24:23 CST 2017
     */
    int updateByPrimaryKey(RefundRequestPo record);
}