package com.ymatou.payment.infrastructure.db.mapper;

import com.ymatou.payment.infrastructure.db.model.RefundmiscrequestlogExample;
import com.ymatou.payment.infrastructure.db.model.RefundmiscrequestlogPo;
import com.ymatou.payment.infrastructure.db.model.RefundmiscrequestlogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RefundmiscrequestlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int countByExample(RefundmiscrequestlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int deleteByExample(RefundmiscrequestlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int deleteByPrimaryKey(String logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int insert(RefundmiscrequestlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int insertSelective(RefundmiscrequestlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    List<RefundmiscrequestlogWithBLOBs> selectByExampleWithBLOBs(RefundmiscrequestlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    List<RefundmiscrequestlogPo> selectByExample(RefundmiscrequestlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    RefundmiscrequestlogWithBLOBs selectByPrimaryKey(String logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") RefundmiscrequestlogWithBLOBs record, @Param("example") RefundmiscrequestlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") RefundmiscrequestlogWithBLOBs record, @Param("example") RefundmiscrequestlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int updateByExample(@Param("record") RefundmiscrequestlogPo record, @Param("example") RefundmiscrequestlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int updateByPrimaryKeySelective(RefundmiscrequestlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(RefundmiscrequestlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RefundMiscRequestLog
     *
     * @mbggenerated Thu May 19 15:10:43 CST 2016
     */
    int updateByPrimaryKey(RefundmiscrequestlogPo record);
}